// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	admin "github.com/loonfs/loonfs-sdk-go/admin"
	core "github.com/loonfs/loonfs-sdk-go/core"
	filesystem "github.com/loonfs/loonfs-sdk-go/filesystem"
	inodes "github.com/loonfs/loonfs-sdk-go/inodes"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	namespaces "github.com/loonfs/loonfs-sdk-go/namespaces"
	option "github.com/loonfs/loonfs-sdk-go/option"
	query "github.com/loonfs/loonfs-sdk-go/query"
	system "github.com/loonfs/loonfs-sdk-go/system"
	uploads "github.com/loonfs/loonfs-sdk-go/uploads"
)

type Client struct {
	WithRawResponse *RawClient
	System          *system.Client
	Admin           *admin.Client
	Namespaces      *namespaces.Client
	Filesystem      *filesystem.Client
	Inodes          *inodes.Client
	Query           *query.Client
	Uploads         *uploads.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		System:          system.NewClient(options),
		Admin:           admin.NewClient(options),
		Namespaces:      namespaces.NewClient(options),
		Filesystem:      filesystem.NewClient(options),
		Inodes:          inodes.NewClient(options),
		Query:           query.NewClient(options),
		Uploads:         uploads.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns a summary of supported features and limits.
//
// Example:
//
//	client.Capabilities(
//	    context.TODO(),
//	)
func (c *Client) Capabilities(
	ctx context.Context,
	opts ...option.RequestOption,
) (*loonfs.CapabilityDocument, error) {
	response, err := c.WithRawResponse.Capabilities(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
