// Code generated by Fern. DO NOT EDIT.

package loonfs

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	listChangesRequestFieldNamespaceID = big.NewInt(1 << 0)
	listChangesRequestFieldAfterSeq    = big.NewInt(1 << 1)
	listChangesRequestFieldLimit       = big.NewInt(1 << 2)
	listChangesRequestFieldSnapshotID  = big.NewInt(1 << 3)
)

type ListChangesRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Return committed changes after this sequence
	AfterSeq ChangeSeq `json:"-" url:"after_seq"`
	// Maximum page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// End the feed at this snapshot's captured sequence
	SnapshotID *PinID `json:"-" url:"snapshot_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListChangesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChangesRequest) SetNamespaceID(namespaceID string) {
	l.NamespaceID = namespaceID
	l.require(listChangesRequestFieldNamespaceID)
}

// SetAfterSeq sets the AfterSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChangesRequest) SetAfterSeq(afterSeq ChangeSeq) {
	l.AfterSeq = afterSeq
	l.require(listChangesRequestFieldAfterSeq)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChangesRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listChangesRequestFieldLimit)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChangesRequest) SetSnapshotID(snapshotID *PinID) {
	l.SnapshotID = snapshotID
	l.require(listChangesRequestFieldSnapshotID)
}

// Change-feed response after a cursor.
var (
	listChangesResponseFieldAfterSeq     = big.NewInt(1 << 0)
	listChangesResponseFieldChanges      = big.NewInt(1 << 1)
	listChangesResponseFieldNamespaceID  = big.NewInt(1 << 2)
	listChangesResponseFieldNextAfterSeq = big.NewInt(1 << 3)
	listChangesResponseFieldThroughSeq   = big.NewInt(1 << 4)
)

type ListChangesResponse struct {
	// Exclusive cursor supplied by the caller, or the endpoint's initial position.
	AfterSeq ChangeSeq `json:"after_seq" url:"after_seq"`
	// Logical commits after `after_seq`, ordered by ascending namespace sequence.
	Changes []*Commit `json:"changes" url:"changes"`
	// Namespace whose ordered commit stream was read.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Cursor to request when another page remains, or `None` at `through_seq`.
	NextAfterSeq *ChangeSeq `json:"next_after_seq,omitempty" url:"next_after_seq,omitempty"`
	// Snapshot head through which this page was evaluated.
	ThroughSeq ChangeSeq `json:"through_seq" url:"through_seq"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListChangesResponse) GetAfterSeq() ChangeSeq {
	if l == nil {
		return 0
	}
	return l.AfterSeq
}

func (l *ListChangesResponse) GetChanges() []*Commit {
	if l == nil {
		return nil
	}
	return l.Changes
}

func (l *ListChangesResponse) GetNamespaceID() NamespaceID {
	if l == nil {
		return ""
	}
	return l.NamespaceID
}

func (l *ListChangesResponse) GetNextAfterSeq() *ChangeSeq {
	if l == nil {
		return nil
	}
	return l.NextAfterSeq
}

func (l *ListChangesResponse) GetThroughSeq() ChangeSeq {
	if l == nil {
		return 0
	}
	return l.ThroughSeq
}

func (l *ListChangesResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListChangesResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAfterSeq sets the AfterSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChangesResponse) SetAfterSeq(afterSeq ChangeSeq) {
	l.AfterSeq = afterSeq
	l.require(listChangesResponseFieldAfterSeq)
}

// SetChanges sets the Changes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChangesResponse) SetChanges(changes []*Commit) {
	l.Changes = changes
	l.require(listChangesResponseFieldChanges)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChangesResponse) SetNamespaceID(namespaceID NamespaceID) {
	l.NamespaceID = namespaceID
	l.require(listChangesResponseFieldNamespaceID)
}

// SetNextAfterSeq sets the NextAfterSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChangesResponse) SetNextAfterSeq(nextAfterSeq *ChangeSeq) {
	l.NextAfterSeq = nextAfterSeq
	l.require(listChangesResponseFieldNextAfterSeq)
}

// SetThroughSeq sets the ThroughSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChangesResponse) SetThroughSeq(throughSeq ChangeSeq) {
	l.ThroughSeq = throughSeq
	l.require(listChangesResponseFieldThroughSeq)
}

func (l *ListChangesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListChangesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListChangesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListChangesResponse) MarshalJSON() ([]byte, error) {
	type embed ListChangesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListChangesResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
