// Code generated by Fern. DO NOT EDIT.

package loonfs

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	commitRequestFieldNamespaceID   = big.NewInt(1 << 0)
	commitRequestFieldActor         = big.NewInt(1 << 1)
	commitRequestFieldCommitID      = big.NewInt(1 << 2)
	commitRequestFieldContentTokens = big.NewInt(1 << 3)
	commitRequestFieldMessage       = big.NewInt(1 << 4)
	commitRequestFieldOperations    = big.NewInt(1 << 5)
)

type CommitRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Actor responsible for the commit, as supplied by the application.
	Actor *ActorRef `json:"actor" url:"-"`
	// Caller-supplied idempotency key for the whole request.
	CommitID CommitID `json:"commit_id" url:"-"`
	// Proofs for any new external content refs introduced by this request.
	// One proof covers every operation that names its content ref.
	ContentTokens []*ContentToken `json:"content_tokens,omitempty" url:"-"`
	// Caller annotation recorded on the commit and reported by the change
	// feed. Part of the commit's identity: reusing `commit_id` with a
	// different message is a `commit_id_reuse_conflict`, exactly as it is
	// for an explicit commit.
	Message *string `json:"message,omitempty" url:"-"`
	// Ordered operations to apply. Must be non-empty; they commit all
	// together or not at all.
	Operations []*FilesystemOperation `json:"operations" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CommitRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitRequest) SetNamespaceID(namespaceID string) {
	c.NamespaceID = namespaceID
	c.require(commitRequestFieldNamespaceID)
}

// SetActor sets the Actor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitRequest) SetActor(actor *ActorRef) {
	c.Actor = actor
	c.require(commitRequestFieldActor)
}

// SetCommitID sets the CommitID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitRequest) SetCommitID(commitID CommitID) {
	c.CommitID = commitID
	c.require(commitRequestFieldCommitID)
}

// SetContentTokens sets the ContentTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitRequest) SetContentTokens(contentTokens []*ContentToken) {
	c.ContentTokens = contentTokens
	c.require(commitRequestFieldContentTokens)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitRequest) SetMessage(message *string) {
	c.Message = message
	c.require(commitRequestFieldMessage)
}

// SetOperations sets the Operations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitRequest) SetOperations(operations []*FilesystemOperation) {
	c.Operations = operations
	c.require(commitRequestFieldOperations)
}

func (c *CommitRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CommitRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CommitRequest(body)
	return nil
}

func (c *CommitRequest) MarshalJSON() ([]byte, error) {
	type embed CommitRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Validated name of one inode attribute.
//
// A key is 1 to 128 UTF-8 bytes and carries no Unicode control
// character, which is also what rejects NUL. Keys are compared exactly:
// nothing case-folds or normalizes them, so two spellings that differ in
// any byte name two different attributes.
//
// The `loonfs.` prefix is reserved for system-owned attributes. This
// type accepts a reserved key, because a durable row has to be able to
// carry a system attribute. The write operation is where a caller's
// attempt to write a reserved key is rejected.
type AttributeKey = string

// Result of one commit.
//
// Every commit resolves to this envelope — path-oriented operations and
// explicit commits, embedded or remote. The commit id is the caller's
// reconciliation handle: resubmitting the same request with the same id
// replays this result instead of committing twice.
//
// The response includes the same attribution and events as
// [`CommittedChange`], including IDs created by the commit.
var (
	commitResponseFieldCommitID      = big.NewInt(1 << 0)
	commitResponseFieldCommittedAtMs = big.NewInt(1 << 1)
	commitResponseFieldCommittedBy   = big.NewInt(1 << 2)
	commitResponseFieldCommittedSeq  = big.NewInt(1 << 3)
	commitResponseFieldEvents        = big.NewInt(1 << 4)
	commitResponseFieldMessage       = big.NewInt(1 << 5)
	commitResponseFieldNamespaceID   = big.NewInt(1 << 6)
)

type CommitResponse struct {
	// Idempotency key the commit landed under: caller-supplied, or
	// generated on the caller's behalf when the request carried none.
	CommitID CommitID `json:"commit_id" url:"commit_id"`
	// Wall-clock stamp of the commit, in Unix milliseconds.
	// Observational: `committed_seq` is the order.
	CommittedAtMs int64 `json:"committed_at_ms" url:"committed_at_ms"`
	// Actor responsible for the commit, as supplied by the application.
	CommittedBy *ActorRef `json:"committed_by" url:"committed_by"`
	// Sequence number where the commit became visible.
	CommittedSeq ChangeSeq `json:"committed_seq" url:"committed_seq"`
	// Semantic filesystem events in commit order. This is omitted only when
	// replaying a commit whose WAL history is no longer retained.
	Events []*FilesystemChange `json:"events,omitempty" url:"events,omitempty"`
	// Caller annotation, omitted when absent and carrying no filesystem
	// semantics.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Namespace that changed.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CommitResponse) GetCommitID() CommitID {
	if c == nil {
		return ""
	}
	return c.CommitID
}

func (c *CommitResponse) GetCommittedAtMs() int64 {
	if c == nil {
		return 0
	}
	return c.CommittedAtMs
}

func (c *CommitResponse) GetCommittedBy() *ActorRef {
	if c == nil {
		return nil
	}
	return c.CommittedBy
}

func (c *CommitResponse) GetCommittedSeq() ChangeSeq {
	if c == nil {
		return 0
	}
	return c.CommittedSeq
}

func (c *CommitResponse) GetEvents() []*FilesystemChange {
	if c == nil {
		return nil
	}
	return c.Events
}

func (c *CommitResponse) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CommitResponse) GetNamespaceID() NamespaceID {
	if c == nil {
		return ""
	}
	return c.NamespaceID
}

func (c *CommitResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CommitResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCommitID sets the CommitID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitResponse) SetCommitID(commitID CommitID) {
	c.CommitID = commitID
	c.require(commitResponseFieldCommitID)
}

// SetCommittedAtMs sets the CommittedAtMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitResponse) SetCommittedAtMs(committedAtMs int64) {
	c.CommittedAtMs = committedAtMs
	c.require(commitResponseFieldCommittedAtMs)
}

// SetCommittedBy sets the CommittedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitResponse) SetCommittedBy(committedBy *ActorRef) {
	c.CommittedBy = committedBy
	c.require(commitResponseFieldCommittedBy)
}

// SetCommittedSeq sets the CommittedSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitResponse) SetCommittedSeq(committedSeq ChangeSeq) {
	c.CommittedSeq = committedSeq
	c.require(commitResponseFieldCommittedSeq)
}

// SetEvents sets the Events field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitResponse) SetEvents(events []*FilesystemChange) {
	c.Events = events
	c.require(commitResponseFieldEvents)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitResponse) SetMessage(message *string) {
	c.Message = message
	c.require(commitResponseFieldMessage)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommitResponse) SetNamespaceID(namespaceID NamespaceID) {
	c.NamespaceID = namespaceID
	c.require(commitResponseFieldNamespaceID)
}

func (c *CommitResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CommitResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CommitResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CommitResponse) MarshalJSON() ([]byte, error) {
	type embed CommitResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CommitResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Directory delete behavior for path-oriented deletes.
type DeleteDirectoryBehavior string

const (
	DeleteDirectoryBehaviorNonRecursive DeleteDirectoryBehavior = "non_recursive"
	DeleteDirectoryBehaviorRecursive    DeleteDirectoryBehavior = "recursive"
)

func NewDeleteDirectoryBehaviorFromString(s string) (DeleteDirectoryBehavior, error) {
	switch s {
	case "non_recursive":
		return DeleteDirectoryBehaviorNonRecursive, nil
	case "recursive":
		return DeleteDirectoryBehaviorRecursive, nil
	}
	var t DeleteDirectoryBehavior
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeleteDirectoryBehavior) Ptr() *DeleteDirectoryBehavior {
	return &d
}

// Destination-conflict behavior for path-oriented puts, moves, and copies.
type DestinationBehavior string

const (
	DestinationBehaviorNoReplace DestinationBehavior = "no_replace"
	DestinationBehaviorReplace   DestinationBehavior = "replace"
)

func NewDestinationBehaviorFromString(s string) (DestinationBehavior, error) {
	switch s {
	case "no_replace":
		return DestinationBehaviorNoReplace, nil
	case "replace":
		return DestinationBehaviorReplace, nil
	}
	var t DestinationBehavior
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DestinationBehavior) Ptr() *DestinationBehavior {
	return &d
}

// One filesystem operation.
//
// Unknown fields are rejected so a misspelled concurrency guard cannot be ignored.
// Fieldless variants must use empty braces so serde rejects unexpected fields.
type FilesystemOperation struct {
	Kind                   string
	CreateDirectory        *FilesystemOperationCreateDirectory
	CreateDirectoryByInode *FilesystemOperationCreateDirectoryByInode
	PutFile                *FilesystemOperationPutFile
	PutFileByInode         *FilesystemOperationPutFileByInode
	PutFileRevisionByInode *FilesystemOperationPutFileRevisionByInode
	DeletePath             *FilesystemOperationDeletePath
	DeleteByInode          *FilesystemOperationDeleteByInode
	MovePath               *FilesystemOperationMovePath
	MoveByInode            *FilesystemOperationMoveByInode
	CopyPath               *FilesystemOperationCopyPath
	Undelete               *FilesystemOperationUndelete
	RestoreRevision        *FilesystemOperationRestoreRevision
	UpdateAttributes       *FilesystemOperationUpdateAttributes

	rawJSON json.RawMessage
}

func (f *FilesystemOperation) GetKind() string {
	if f == nil {
		return ""
	}
	return f.Kind
}

func (f *FilesystemOperation) GetCreateDirectory() *FilesystemOperationCreateDirectory {
	if f == nil {
		return nil
	}
	return f.CreateDirectory
}

func (f *FilesystemOperation) GetCreateDirectoryByInode() *FilesystemOperationCreateDirectoryByInode {
	if f == nil {
		return nil
	}
	return f.CreateDirectoryByInode
}

func (f *FilesystemOperation) GetPutFile() *FilesystemOperationPutFile {
	if f == nil {
		return nil
	}
	return f.PutFile
}

func (f *FilesystemOperation) GetPutFileByInode() *FilesystemOperationPutFileByInode {
	if f == nil {
		return nil
	}
	return f.PutFileByInode
}

func (f *FilesystemOperation) GetPutFileRevisionByInode() *FilesystemOperationPutFileRevisionByInode {
	if f == nil {
		return nil
	}
	return f.PutFileRevisionByInode
}

func (f *FilesystemOperation) GetDeletePath() *FilesystemOperationDeletePath {
	if f == nil {
		return nil
	}
	return f.DeletePath
}

func (f *FilesystemOperation) GetDeleteByInode() *FilesystemOperationDeleteByInode {
	if f == nil {
		return nil
	}
	return f.DeleteByInode
}

func (f *FilesystemOperation) GetMovePath() *FilesystemOperationMovePath {
	if f == nil {
		return nil
	}
	return f.MovePath
}

func (f *FilesystemOperation) GetMoveByInode() *FilesystemOperationMoveByInode {
	if f == nil {
		return nil
	}
	return f.MoveByInode
}

func (f *FilesystemOperation) GetCopyPath() *FilesystemOperationCopyPath {
	if f == nil {
		return nil
	}
	return f.CopyPath
}

func (f *FilesystemOperation) GetUndelete() *FilesystemOperationUndelete {
	if f == nil {
		return nil
	}
	return f.Undelete
}

func (f *FilesystemOperation) GetRestoreRevision() *FilesystemOperationRestoreRevision {
	if f == nil {
		return nil
	}
	return f.RestoreRevision
}

func (f *FilesystemOperation) GetUpdateAttributes() *FilesystemOperationUpdateAttributes {
	if f == nil {
		return nil
	}
	return f.UpdateAttributes
}

func (f *FilesystemOperation) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	f.Kind = unmarshaler.Kind
	if unmarshaler.Kind == "" {
		return fmt.Errorf("%T did not include discriminant kind", f)
	}
	switch unmarshaler.Kind {
	case "create_directory":
		value := new(FilesystemOperationCreateDirectory)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.CreateDirectory = value
	case "create_directory_by_inode":
		value := new(FilesystemOperationCreateDirectoryByInode)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.CreateDirectoryByInode = value
	case "put_file":
		value := new(FilesystemOperationPutFile)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.PutFile = value
	case "put_file_by_inode":
		value := new(FilesystemOperationPutFileByInode)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.PutFileByInode = value
	case "put_file_revision_by_inode":
		value := new(FilesystemOperationPutFileRevisionByInode)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.PutFileRevisionByInode = value
	case "delete_path":
		value := new(FilesystemOperationDeletePath)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.DeletePath = value
	case "delete_by_inode":
		value := new(FilesystemOperationDeleteByInode)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.DeleteByInode = value
	case "move_path":
		value := new(FilesystemOperationMovePath)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.MovePath = value
	case "move_by_inode":
		value := new(FilesystemOperationMoveByInode)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.MoveByInode = value
	case "copy_path":
		value := new(FilesystemOperationCopyPath)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.CopyPath = value
	case "undelete":
		value := new(FilesystemOperationUndelete)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.Undelete = value
	case "restore_revision":
		value := new(FilesystemOperationRestoreRevision)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.RestoreRevision = value
	case "update_attributes":
		value := new(FilesystemOperationUpdateAttributes)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.UpdateAttributes = value
	}
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f FilesystemOperation) MarshalJSON() ([]byte, error) {
	if err := f.validate(); err != nil {
		return nil, err
	}
	if f.CreateDirectory != nil {
		return internal.MarshalJSONWithExtraProperty(f.CreateDirectory, "kind", "create_directory")
	}
	if f.CreateDirectoryByInode != nil {
		return internal.MarshalJSONWithExtraProperty(f.CreateDirectoryByInode, "kind", "create_directory_by_inode")
	}
	if f.PutFile != nil {
		return internal.MarshalJSONWithExtraProperty(f.PutFile, "kind", "put_file")
	}
	if f.PutFileByInode != nil {
		return internal.MarshalJSONWithExtraProperty(f.PutFileByInode, "kind", "put_file_by_inode")
	}
	if f.PutFileRevisionByInode != nil {
		return internal.MarshalJSONWithExtraProperty(f.PutFileRevisionByInode, "kind", "put_file_revision_by_inode")
	}
	if f.DeletePath != nil {
		return internal.MarshalJSONWithExtraProperty(f.DeletePath, "kind", "delete_path")
	}
	if f.DeleteByInode != nil {
		return internal.MarshalJSONWithExtraProperty(f.DeleteByInode, "kind", "delete_by_inode")
	}
	if f.MovePath != nil {
		return internal.MarshalJSONWithExtraProperty(f.MovePath, "kind", "move_path")
	}
	if f.MoveByInode != nil {
		return internal.MarshalJSONWithExtraProperty(f.MoveByInode, "kind", "move_by_inode")
	}
	if f.CopyPath != nil {
		return internal.MarshalJSONWithExtraProperty(f.CopyPath, "kind", "copy_path")
	}
	if f.Undelete != nil {
		return internal.MarshalJSONWithExtraProperty(f.Undelete, "kind", "undelete")
	}
	if f.RestoreRevision != nil {
		return internal.MarshalJSONWithExtraProperty(f.RestoreRevision, "kind", "restore_revision")
	}
	if f.UpdateAttributes != nil {
		return internal.MarshalJSONWithExtraProperty(f.UpdateAttributes, "kind", "update_attributes")
	}
	if len(f.rawJSON) > 0 {
		return f.rawJSON, nil
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", f)
}

type FilesystemOperationVisitor interface {
	VisitCreateDirectory(*FilesystemOperationCreateDirectory) error
	VisitCreateDirectoryByInode(*FilesystemOperationCreateDirectoryByInode) error
	VisitPutFile(*FilesystemOperationPutFile) error
	VisitPutFileByInode(*FilesystemOperationPutFileByInode) error
	VisitPutFileRevisionByInode(*FilesystemOperationPutFileRevisionByInode) error
	VisitDeletePath(*FilesystemOperationDeletePath) error
	VisitDeleteByInode(*FilesystemOperationDeleteByInode) error
	VisitMovePath(*FilesystemOperationMovePath) error
	VisitMoveByInode(*FilesystemOperationMoveByInode) error
	VisitCopyPath(*FilesystemOperationCopyPath) error
	VisitUndelete(*FilesystemOperationUndelete) error
	VisitRestoreRevision(*FilesystemOperationRestoreRevision) error
	VisitUpdateAttributes(*FilesystemOperationUpdateAttributes) error
}

func (f *FilesystemOperation) Accept(visitor FilesystemOperationVisitor) error {
	if f.CreateDirectory != nil {
		return visitor.VisitCreateDirectory(f.CreateDirectory)
	}
	if f.CreateDirectoryByInode != nil {
		return visitor.VisitCreateDirectoryByInode(f.CreateDirectoryByInode)
	}
	if f.PutFile != nil {
		return visitor.VisitPutFile(f.PutFile)
	}
	if f.PutFileByInode != nil {
		return visitor.VisitPutFileByInode(f.PutFileByInode)
	}
	if f.PutFileRevisionByInode != nil {
		return visitor.VisitPutFileRevisionByInode(f.PutFileRevisionByInode)
	}
	if f.DeletePath != nil {
		return visitor.VisitDeletePath(f.DeletePath)
	}
	if f.DeleteByInode != nil {
		return visitor.VisitDeleteByInode(f.DeleteByInode)
	}
	if f.MovePath != nil {
		return visitor.VisitMovePath(f.MovePath)
	}
	if f.MoveByInode != nil {
		return visitor.VisitMoveByInode(f.MoveByInode)
	}
	if f.CopyPath != nil {
		return visitor.VisitCopyPath(f.CopyPath)
	}
	if f.Undelete != nil {
		return visitor.VisitUndelete(f.Undelete)
	}
	if f.RestoreRevision != nil {
		return visitor.VisitRestoreRevision(f.RestoreRevision)
	}
	if f.UpdateAttributes != nil {
		return visitor.VisitUpdateAttributes(f.UpdateAttributes)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", f)
}

func (f *FilesystemOperation) validate() error {
	if f == nil {
		return fmt.Errorf("type %T is nil", f)
	}
	var fields []string
	if f.CreateDirectory != nil {
		fields = append(fields, "create_directory")
	}
	if f.CreateDirectoryByInode != nil {
		fields = append(fields, "create_directory_by_inode")
	}
	if f.PutFile != nil {
		fields = append(fields, "put_file")
	}
	if f.PutFileByInode != nil {
		fields = append(fields, "put_file_by_inode")
	}
	if f.PutFileRevisionByInode != nil {
		fields = append(fields, "put_file_revision_by_inode")
	}
	if f.DeletePath != nil {
		fields = append(fields, "delete_path")
	}
	if f.DeleteByInode != nil {
		fields = append(fields, "delete_by_inode")
	}
	if f.MovePath != nil {
		fields = append(fields, "move_path")
	}
	if f.MoveByInode != nil {
		fields = append(fields, "move_by_inode")
	}
	if f.CopyPath != nil {
		fields = append(fields, "copy_path")
	}
	if f.Undelete != nil {
		fields = append(fields, "undelete")
	}
	if f.RestoreRevision != nil {
		fields = append(fields, "restore_revision")
	}
	if f.UpdateAttributes != nil {
		fields = append(fields, "update_attributes")
	}
	if len(fields) == 0 {
		if f.Kind != "" {
			if len(f.rawJSON) > 0 {
				return nil
			}
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", f, f.Kind)
		}
		return fmt.Errorf("type %T is empty", f)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", f, fields)
	}
	if f.Kind != "" {
		field := fields[0]
		if f.Kind != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				f,
				f.Kind,
				f,
			)
		}
	}
	return nil
}

// Copy one file path to another path.
var (
	filesystemOperationCopyPathFieldBehavior                      = big.NewInt(1 << 0)
	filesystemOperationCopyPathFieldExpectedDestinationInodeID    = big.NewInt(1 << 1)
	filesystemOperationCopyPathFieldExpectedDestinationRevisionNo = big.NewInt(1 << 2)
	filesystemOperationCopyPathFieldFromPath                      = big.NewInt(1 << 3)
	filesystemOperationCopyPathFieldToPath                        = big.NewInt(1 << 4)
)

type FilesystemOperationCopyPath struct {
	// Whether an existing destination file may receive a copied revision.
	Behavior *DestinationBehavior `json:"behavior,omitempty" url:"behavior,omitempty"`
	// Stable inode ID within a namespace
	ExpectedDestinationInodeID *string `json:"expected_destination_inode_id,omitempty" url:"expected_destination_inode_id,omitempty"`
	// With `replace` behavior and an inode guard, the request requires this content revision.
	ExpectedDestinationRevisionNo *RevisionNo `json:"expected_destination_revision_no,omitempty" url:"expected_destination_revision_no,omitempty"`
	// Absolute source path that must resolve to a visible file.
	FromPath AbsolutePath `json:"from_path" url:"from_path"`
	// Absolute destination whose parent must be visible and writable.
	ToPath AbsolutePath `json:"to_path" url:"to_path"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationCopyPath) GetBehavior() *DestinationBehavior {
	if f == nil {
		return nil
	}
	return f.Behavior
}

func (f *FilesystemOperationCopyPath) GetExpectedDestinationInodeID() *string {
	if f == nil {
		return nil
	}
	return f.ExpectedDestinationInodeID
}

func (f *FilesystemOperationCopyPath) GetExpectedDestinationRevisionNo() *RevisionNo {
	if f == nil {
		return nil
	}
	return f.ExpectedDestinationRevisionNo
}

func (f *FilesystemOperationCopyPath) GetFromPath() AbsolutePath {
	if f == nil {
		return ""
	}
	return f.FromPath
}

func (f *FilesystemOperationCopyPath) GetToPath() AbsolutePath {
	if f == nil {
		return ""
	}
	return f.ToPath
}

func (f *FilesystemOperationCopyPath) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationCopyPath) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetBehavior sets the Behavior field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationCopyPath) SetBehavior(behavior *DestinationBehavior) {
	f.Behavior = behavior
	f.require(filesystemOperationCopyPathFieldBehavior)
}

// SetExpectedDestinationInodeID sets the ExpectedDestinationInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationCopyPath) SetExpectedDestinationInodeID(expectedDestinationInodeID *string) {
	f.ExpectedDestinationInodeID = expectedDestinationInodeID
	f.require(filesystemOperationCopyPathFieldExpectedDestinationInodeID)
}

// SetExpectedDestinationRevisionNo sets the ExpectedDestinationRevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationCopyPath) SetExpectedDestinationRevisionNo(expectedDestinationRevisionNo *RevisionNo) {
	f.ExpectedDestinationRevisionNo = expectedDestinationRevisionNo
	f.require(filesystemOperationCopyPathFieldExpectedDestinationRevisionNo)
}

// SetFromPath sets the FromPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationCopyPath) SetFromPath(fromPath AbsolutePath) {
	f.FromPath = fromPath
	f.require(filesystemOperationCopyPathFieldFromPath)
}

// SetToPath sets the ToPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationCopyPath) SetToPath(toPath AbsolutePath) {
	f.ToPath = toPath
	f.require(filesystemOperationCopyPathFieldToPath)
}

func (f *FilesystemOperationCopyPath) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationCopyPath
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationCopyPath(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationCopyPath) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationCopyPath
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationCopyPath) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Create one directory.
var (
	filesystemOperationCreateDirectoryFieldParents = big.NewInt(1 << 0)
	filesystemOperationCreateDirectoryFieldPath    = big.NewInt(1 << 1)
)

type FilesystemOperationCreateDirectory struct {
	// Also create missing ancestor directories (the same auto-create
	// `put_file` performs). The final component must still be new.
	Parents *bool `json:"parents,omitempty" url:"parents,omitempty"`
	// Absolute destination path, rejected when invalid or already bound.
	Path AbsolutePath `json:"path" url:"path"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationCreateDirectory) GetParents() *bool {
	if f == nil {
		return nil
	}
	return f.Parents
}

func (f *FilesystemOperationCreateDirectory) GetPath() AbsolutePath {
	if f == nil {
		return ""
	}
	return f.Path
}

func (f *FilesystemOperationCreateDirectory) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationCreateDirectory) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetParents sets the Parents field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationCreateDirectory) SetParents(parents *bool) {
	f.Parents = parents
	f.require(filesystemOperationCreateDirectoryFieldParents)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationCreateDirectory) SetPath(path AbsolutePath) {
	f.Path = path
	f.require(filesystemOperationCreateDirectoryFieldPath)
}

func (f *FilesystemOperationCreateDirectory) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationCreateDirectory
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationCreateDirectory(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationCreateDirectory) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationCreateDirectory
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationCreateDirectory) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Create a directory under an existing parent inode.
var (
	filesystemOperationCreateDirectoryByInodeFieldDisplayName   = big.NewInt(1 << 0)
	filesystemOperationCreateDirectoryByInodeFieldParentInodeID = big.NewInt(1 << 1)
)

type FilesystemOperationCreateDirectoryByInode struct {
	// New directory name.
	DisplayName DisplayName `json:"display_name" url:"display_name"`
	// Stable inode ID within a namespace
	ParentInodeID string `json:"parent_inode_id" url:"parent_inode_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationCreateDirectoryByInode) GetDisplayName() DisplayName {
	if f == nil {
		return ""
	}
	return f.DisplayName
}

func (f *FilesystemOperationCreateDirectoryByInode) GetParentInodeID() string {
	if f == nil {
		return ""
	}
	return f.ParentInodeID
}

func (f *FilesystemOperationCreateDirectoryByInode) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationCreateDirectoryByInode) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationCreateDirectoryByInode) SetDisplayName(displayName DisplayName) {
	f.DisplayName = displayName
	f.require(filesystemOperationCreateDirectoryByInodeFieldDisplayName)
}

// SetParentInodeID sets the ParentInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationCreateDirectoryByInode) SetParentInodeID(parentInodeID string) {
	f.ParentInodeID = parentInodeID
	f.require(filesystemOperationCreateDirectoryByInodeFieldParentInodeID)
}

func (f *FilesystemOperationCreateDirectoryByInode) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationCreateDirectoryByInode
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationCreateDirectoryByInode(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationCreateDirectoryByInode) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationCreateDirectoryByInode
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationCreateDirectoryByInode) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Delete an inode if its current binding matches.
var (
	filesystemOperationDeleteByInodeFieldBehavior                  = big.NewInt(1 << 0)
	filesystemOperationDeleteByInodeFieldExpectedBindingGeneration = big.NewInt(1 << 1)
	filesystemOperationDeleteByInodeFieldInodeID                   = big.NewInt(1 << 2)
)

type FilesystemOperationDeleteByInode struct {
	// Whether a non-empty directory may be tombstoned recursively.
	Behavior *DeleteDirectoryBehavior `json:"behavior,omitempty" url:"behavior,omitempty"`
	// Binding generation required for the delete.
	ExpectedBindingGeneration string `json:"expected_binding_generation" url:"expected_binding_generation"`
	// Stable inode ID within a namespace
	InodeID string `json:"inode_id" url:"inode_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationDeleteByInode) GetBehavior() *DeleteDirectoryBehavior {
	if f == nil {
		return nil
	}
	return f.Behavior
}

func (f *FilesystemOperationDeleteByInode) GetExpectedBindingGeneration() string {
	if f == nil {
		return ""
	}
	return f.ExpectedBindingGeneration
}

func (f *FilesystemOperationDeleteByInode) GetInodeID() string {
	if f == nil {
		return ""
	}
	return f.InodeID
}

func (f *FilesystemOperationDeleteByInode) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationDeleteByInode) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetBehavior sets the Behavior field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationDeleteByInode) SetBehavior(behavior *DeleteDirectoryBehavior) {
	f.Behavior = behavior
	f.require(filesystemOperationDeleteByInodeFieldBehavior)
}

// SetExpectedBindingGeneration sets the ExpectedBindingGeneration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationDeleteByInode) SetExpectedBindingGeneration(expectedBindingGeneration string) {
	f.ExpectedBindingGeneration = expectedBindingGeneration
	f.require(filesystemOperationDeleteByInodeFieldExpectedBindingGeneration)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationDeleteByInode) SetInodeID(inodeID string) {
	f.InodeID = inodeID
	f.require(filesystemOperationDeleteByInodeFieldInodeID)
}

func (f *FilesystemOperationDeleteByInode) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationDeleteByInode
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationDeleteByInode(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationDeleteByInode) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationDeleteByInode
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationDeleteByInode) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Delete one path.
var (
	filesystemOperationDeletePathFieldBehavior        = big.NewInt(1 << 0)
	filesystemOperationDeletePathFieldExpectedInodeID = big.NewInt(1 << 1)
	filesystemOperationDeletePathFieldPath            = big.NewInt(1 << 2)
)

type FilesystemOperationDeletePath struct {
	// Whether a non-empty directory may be tombstoned recursively.
	Behavior *DeleteDirectoryBehavior `json:"behavior,omitempty" url:"behavior,omitempty"`
	// Stable inode ID within a namespace
	ExpectedInodeID *string `json:"expected_inode_id,omitempty" url:"expected_inode_id,omitempty"`
	// Absolute path that must resolve to a visible inode.
	Path AbsolutePath `json:"path" url:"path"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationDeletePath) GetBehavior() *DeleteDirectoryBehavior {
	if f == nil {
		return nil
	}
	return f.Behavior
}

func (f *FilesystemOperationDeletePath) GetExpectedInodeID() *string {
	if f == nil {
		return nil
	}
	return f.ExpectedInodeID
}

func (f *FilesystemOperationDeletePath) GetPath() AbsolutePath {
	if f == nil {
		return ""
	}
	return f.Path
}

func (f *FilesystemOperationDeletePath) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationDeletePath) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetBehavior sets the Behavior field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationDeletePath) SetBehavior(behavior *DeleteDirectoryBehavior) {
	f.Behavior = behavior
	f.require(filesystemOperationDeletePathFieldBehavior)
}

// SetExpectedInodeID sets the ExpectedInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationDeletePath) SetExpectedInodeID(expectedInodeID *string) {
	f.ExpectedInodeID = expectedInodeID
	f.require(filesystemOperationDeletePathFieldExpectedInodeID)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationDeletePath) SetPath(path AbsolutePath) {
	f.Path = path
	f.require(filesystemOperationDeletePathFieldPath)
}

func (f *FilesystemOperationDeletePath) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationDeletePath
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationDeletePath(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationDeletePath) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationDeletePath
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationDeletePath) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Move an inode if its current binding matches.
var (
	filesystemOperationMoveByInodeFieldBehavior                      = big.NewInt(1 << 0)
	filesystemOperationMoveByInodeFieldExpectedBindingGeneration     = big.NewInt(1 << 1)
	filesystemOperationMoveByInodeFieldExpectedDestinationInodeID    = big.NewInt(1 << 2)
	filesystemOperationMoveByInodeFieldExpectedDestinationRevisionNo = big.NewInt(1 << 3)
	filesystemOperationMoveByInodeFieldInodeID                       = big.NewInt(1 << 4)
	filesystemOperationMoveByInodeFieldToDisplayName                 = big.NewInt(1 << 5)
	filesystemOperationMoveByInodeFieldToParentInodeID               = big.NewInt(1 << 6)
)

type FilesystemOperationMoveByInode struct {
	// Whether an existing destination file may be replaced.
	Behavior *DestinationBehavior `json:"behavior,omitempty" url:"behavior,omitempty"`
	// Binding generation required for the move.
	ExpectedBindingGeneration string `json:"expected_binding_generation" url:"expected_binding_generation"`
	// Stable inode ID within a namespace
	ExpectedDestinationInodeID *string `json:"expected_destination_inode_id,omitempty" url:"expected_destination_inode_id,omitempty"`
	// With `replace` behavior and an inode guard, the request requires this content revision.
	ExpectedDestinationRevisionNo *RevisionNo `json:"expected_destination_revision_no,omitempty" url:"expected_destination_revision_no,omitempty"`
	// Stable inode ID within a namespace
	InodeID string `json:"inode_id" url:"inode_id"`
	// New name.
	ToDisplayName DisplayName `json:"to_display_name" url:"to_display_name"`
	// Stable inode ID within a namespace
	ToParentInodeID string `json:"to_parent_inode_id" url:"to_parent_inode_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationMoveByInode) GetBehavior() *DestinationBehavior {
	if f == nil {
		return nil
	}
	return f.Behavior
}

func (f *FilesystemOperationMoveByInode) GetExpectedBindingGeneration() string {
	if f == nil {
		return ""
	}
	return f.ExpectedBindingGeneration
}

func (f *FilesystemOperationMoveByInode) GetExpectedDestinationInodeID() *string {
	if f == nil {
		return nil
	}
	return f.ExpectedDestinationInodeID
}

func (f *FilesystemOperationMoveByInode) GetExpectedDestinationRevisionNo() *RevisionNo {
	if f == nil {
		return nil
	}
	return f.ExpectedDestinationRevisionNo
}

func (f *FilesystemOperationMoveByInode) GetInodeID() string {
	if f == nil {
		return ""
	}
	return f.InodeID
}

func (f *FilesystemOperationMoveByInode) GetToDisplayName() DisplayName {
	if f == nil {
		return ""
	}
	return f.ToDisplayName
}

func (f *FilesystemOperationMoveByInode) GetToParentInodeID() string {
	if f == nil {
		return ""
	}
	return f.ToParentInodeID
}

func (f *FilesystemOperationMoveByInode) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationMoveByInode) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetBehavior sets the Behavior field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMoveByInode) SetBehavior(behavior *DestinationBehavior) {
	f.Behavior = behavior
	f.require(filesystemOperationMoveByInodeFieldBehavior)
}

// SetExpectedBindingGeneration sets the ExpectedBindingGeneration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMoveByInode) SetExpectedBindingGeneration(expectedBindingGeneration string) {
	f.ExpectedBindingGeneration = expectedBindingGeneration
	f.require(filesystemOperationMoveByInodeFieldExpectedBindingGeneration)
}

// SetExpectedDestinationInodeID sets the ExpectedDestinationInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMoveByInode) SetExpectedDestinationInodeID(expectedDestinationInodeID *string) {
	f.ExpectedDestinationInodeID = expectedDestinationInodeID
	f.require(filesystemOperationMoveByInodeFieldExpectedDestinationInodeID)
}

// SetExpectedDestinationRevisionNo sets the ExpectedDestinationRevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMoveByInode) SetExpectedDestinationRevisionNo(expectedDestinationRevisionNo *RevisionNo) {
	f.ExpectedDestinationRevisionNo = expectedDestinationRevisionNo
	f.require(filesystemOperationMoveByInodeFieldExpectedDestinationRevisionNo)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMoveByInode) SetInodeID(inodeID string) {
	f.InodeID = inodeID
	f.require(filesystemOperationMoveByInodeFieldInodeID)
}

// SetToDisplayName sets the ToDisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMoveByInode) SetToDisplayName(toDisplayName DisplayName) {
	f.ToDisplayName = toDisplayName
	f.require(filesystemOperationMoveByInodeFieldToDisplayName)
}

// SetToParentInodeID sets the ToParentInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMoveByInode) SetToParentInodeID(toParentInodeID string) {
	f.ToParentInodeID = toParentInodeID
	f.require(filesystemOperationMoveByInodeFieldToParentInodeID)
}

func (f *FilesystemOperationMoveByInode) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationMoveByInode
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationMoveByInode(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationMoveByInode) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationMoveByInode
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationMoveByInode) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Move one path to another path.
var (
	filesystemOperationMovePathFieldBehavior                      = big.NewInt(1 << 0)
	filesystemOperationMovePathFieldExpectedDestinationInodeID    = big.NewInt(1 << 1)
	filesystemOperationMovePathFieldExpectedDestinationRevisionNo = big.NewInt(1 << 2)
	filesystemOperationMovePathFieldFromPath                      = big.NewInt(1 << 3)
	filesystemOperationMovePathFieldToPath                        = big.NewInt(1 << 4)
)

type FilesystemOperationMovePath struct {
	// Whether an existing destination file may be replaced.
	Behavior *DestinationBehavior `json:"behavior,omitempty" url:"behavior,omitempty"`
	// Stable inode ID within a namespace
	ExpectedDestinationInodeID *string `json:"expected_destination_inode_id,omitempty" url:"expected_destination_inode_id,omitempty"`
	// With `replace` behavior and an inode guard, the request requires this content revision.
	ExpectedDestinationRevisionNo *RevisionNo `json:"expected_destination_revision_no,omitempty" url:"expected_destination_revision_no,omitempty"`
	// Absolute source path that must resolve to a visible inode.
	FromPath AbsolutePath `json:"from_path" url:"from_path"`
	// Absolute destination whose parent must be visible and writable.
	ToPath AbsolutePath `json:"to_path" url:"to_path"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationMovePath) GetBehavior() *DestinationBehavior {
	if f == nil {
		return nil
	}
	return f.Behavior
}

func (f *FilesystemOperationMovePath) GetExpectedDestinationInodeID() *string {
	if f == nil {
		return nil
	}
	return f.ExpectedDestinationInodeID
}

func (f *FilesystemOperationMovePath) GetExpectedDestinationRevisionNo() *RevisionNo {
	if f == nil {
		return nil
	}
	return f.ExpectedDestinationRevisionNo
}

func (f *FilesystemOperationMovePath) GetFromPath() AbsolutePath {
	if f == nil {
		return ""
	}
	return f.FromPath
}

func (f *FilesystemOperationMovePath) GetToPath() AbsolutePath {
	if f == nil {
		return ""
	}
	return f.ToPath
}

func (f *FilesystemOperationMovePath) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationMovePath) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetBehavior sets the Behavior field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMovePath) SetBehavior(behavior *DestinationBehavior) {
	f.Behavior = behavior
	f.require(filesystemOperationMovePathFieldBehavior)
}

// SetExpectedDestinationInodeID sets the ExpectedDestinationInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMovePath) SetExpectedDestinationInodeID(expectedDestinationInodeID *string) {
	f.ExpectedDestinationInodeID = expectedDestinationInodeID
	f.require(filesystemOperationMovePathFieldExpectedDestinationInodeID)
}

// SetExpectedDestinationRevisionNo sets the ExpectedDestinationRevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMovePath) SetExpectedDestinationRevisionNo(expectedDestinationRevisionNo *RevisionNo) {
	f.ExpectedDestinationRevisionNo = expectedDestinationRevisionNo
	f.require(filesystemOperationMovePathFieldExpectedDestinationRevisionNo)
}

// SetFromPath sets the FromPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMovePath) SetFromPath(fromPath AbsolutePath) {
	f.FromPath = fromPath
	f.require(filesystemOperationMovePathFieldFromPath)
}

// SetToPath sets the ToPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationMovePath) SetToPath(toPath AbsolutePath) {
	f.ToPath = toPath
	f.require(filesystemOperationMovePathFieldToPath)
}

func (f *FilesystemOperationMovePath) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationMovePath
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationMovePath(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationMovePath) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationMovePath
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationMovePath) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Create or replace one file with an already-durable content ref.
var (
	filesystemOperationPutFileFieldBehavior           = big.NewInt(1 << 0)
	filesystemOperationPutFileFieldContentRef         = big.NewInt(1 << 1)
	filesystemOperationPutFileFieldExpectedInodeID    = big.NewInt(1 << 2)
	filesystemOperationPutFileFieldExpectedRevisionNo = big.NewInt(1 << 3)
	filesystemOperationPutFileFieldPath               = big.NewInt(1 << 4)
)

type FilesystemOperationPutFile struct {
	// Whether an existing file may receive a new revision instead of causing a conflict.
	Behavior *DestinationBehavior `json:"behavior,omitempty" url:"behavior,omitempty"`
	// Immutable bytes that must be covered by a valid preparation proof.
	ContentRef *ContentRef `json:"content_ref" url:"content_ref"`
	// Stable inode ID within a namespace
	ExpectedInodeID *string `json:"expected_inode_id,omitempty" url:"expected_inode_id,omitempty"`
	// With `replace` behavior and an inode guard, the request requires this content revision.
	ExpectedRevisionNo *RevisionNo `json:"expected_revision_no,omitempty" url:"expected_revision_no,omitempty"`
	// Absolute destination path; missing ancestors are created automatically.
	Path AbsolutePath `json:"path" url:"path"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationPutFile) GetBehavior() *DestinationBehavior {
	if f == nil {
		return nil
	}
	return f.Behavior
}

func (f *FilesystemOperationPutFile) GetContentRef() *ContentRef {
	if f == nil {
		return nil
	}
	return f.ContentRef
}

func (f *FilesystemOperationPutFile) GetExpectedInodeID() *string {
	if f == nil {
		return nil
	}
	return f.ExpectedInodeID
}

func (f *FilesystemOperationPutFile) GetExpectedRevisionNo() *RevisionNo {
	if f == nil {
		return nil
	}
	return f.ExpectedRevisionNo
}

func (f *FilesystemOperationPutFile) GetPath() AbsolutePath {
	if f == nil {
		return ""
	}
	return f.Path
}

func (f *FilesystemOperationPutFile) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationPutFile) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetBehavior sets the Behavior field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFile) SetBehavior(behavior *DestinationBehavior) {
	f.Behavior = behavior
	f.require(filesystemOperationPutFileFieldBehavior)
}

// SetContentRef sets the ContentRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFile) SetContentRef(contentRef *ContentRef) {
	f.ContentRef = contentRef
	f.require(filesystemOperationPutFileFieldContentRef)
}

// SetExpectedInodeID sets the ExpectedInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFile) SetExpectedInodeID(expectedInodeID *string) {
	f.ExpectedInodeID = expectedInodeID
	f.require(filesystemOperationPutFileFieldExpectedInodeID)
}

// SetExpectedRevisionNo sets the ExpectedRevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFile) SetExpectedRevisionNo(expectedRevisionNo *RevisionNo) {
	f.ExpectedRevisionNo = expectedRevisionNo
	f.require(filesystemOperationPutFileFieldExpectedRevisionNo)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFile) SetPath(path AbsolutePath) {
	f.Path = path
	f.require(filesystemOperationPutFileFieldPath)
}

func (f *FilesystemOperationPutFile) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationPutFile
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationPutFile(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationPutFile) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationPutFile
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationPutFile) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Create a file under an existing parent inode. The name must be unused.
var (
	filesystemOperationPutFileByInodeFieldContentRef    = big.NewInt(1 << 0)
	filesystemOperationPutFileByInodeFieldDisplayName   = big.NewInt(1 << 1)
	filesystemOperationPutFileByInodeFieldParentInodeID = big.NewInt(1 << 2)
)

type FilesystemOperationPutFileByInode struct {
	// Immutable bytes that must be covered by a valid preparation proof.
	ContentRef *ContentRef `json:"content_ref" url:"content_ref"`
	// New file name.
	DisplayName DisplayName `json:"display_name" url:"display_name"`
	// Stable inode ID within a namespace
	ParentInodeID string `json:"parent_inode_id" url:"parent_inode_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationPutFileByInode) GetContentRef() *ContentRef {
	if f == nil {
		return nil
	}
	return f.ContentRef
}

func (f *FilesystemOperationPutFileByInode) GetDisplayName() DisplayName {
	if f == nil {
		return ""
	}
	return f.DisplayName
}

func (f *FilesystemOperationPutFileByInode) GetParentInodeID() string {
	if f == nil {
		return ""
	}
	return f.ParentInodeID
}

func (f *FilesystemOperationPutFileByInode) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationPutFileByInode) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetContentRef sets the ContentRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFileByInode) SetContentRef(contentRef *ContentRef) {
	f.ContentRef = contentRef
	f.require(filesystemOperationPutFileByInodeFieldContentRef)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFileByInode) SetDisplayName(displayName DisplayName) {
	f.DisplayName = displayName
	f.require(filesystemOperationPutFileByInodeFieldDisplayName)
}

// SetParentInodeID sets the ParentInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFileByInode) SetParentInodeID(parentInodeID string) {
	f.ParentInodeID = parentInodeID
	f.require(filesystemOperationPutFileByInodeFieldParentInodeID)
}

func (f *FilesystemOperationPutFileByInode) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationPutFileByInode
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationPutFileByInode(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationPutFileByInode) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationPutFileByInode
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationPutFileByInode) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Append a revision to a file inode if its current revision matches.
var (
	filesystemOperationPutFileRevisionByInodeFieldContentRef         = big.NewInt(1 << 0)
	filesystemOperationPutFileRevisionByInodeFieldExpectedRevisionNo = big.NewInt(1 << 1)
	filesystemOperationPutFileRevisionByInodeFieldInodeID            = big.NewInt(1 << 2)
)

type FilesystemOperationPutFileRevisionByInode struct {
	// Immutable bytes that must be covered by a valid preparation proof.
	ContentRef *ContentRef `json:"content_ref" url:"content_ref"`
	// Current revision required for the write.
	ExpectedRevisionNo RevisionNo `json:"expected_revision_no" url:"expected_revision_no"`
	// Stable inode ID within a namespace
	InodeID string `json:"inode_id" url:"inode_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationPutFileRevisionByInode) GetContentRef() *ContentRef {
	if f == nil {
		return nil
	}
	return f.ContentRef
}

func (f *FilesystemOperationPutFileRevisionByInode) GetExpectedRevisionNo() RevisionNo {
	if f == nil {
		return 0
	}
	return f.ExpectedRevisionNo
}

func (f *FilesystemOperationPutFileRevisionByInode) GetInodeID() string {
	if f == nil {
		return ""
	}
	return f.InodeID
}

func (f *FilesystemOperationPutFileRevisionByInode) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationPutFileRevisionByInode) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetContentRef sets the ContentRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFileRevisionByInode) SetContentRef(contentRef *ContentRef) {
	f.ContentRef = contentRef
	f.require(filesystemOperationPutFileRevisionByInodeFieldContentRef)
}

// SetExpectedRevisionNo sets the ExpectedRevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFileRevisionByInode) SetExpectedRevisionNo(expectedRevisionNo RevisionNo) {
	f.ExpectedRevisionNo = expectedRevisionNo
	f.require(filesystemOperationPutFileRevisionByInodeFieldExpectedRevisionNo)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationPutFileRevisionByInode) SetInodeID(inodeID string) {
	f.InodeID = inodeID
	f.require(filesystemOperationPutFileRevisionByInodeFieldInodeID)
}

func (f *FilesystemOperationPutFileRevisionByInode) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationPutFileRevisionByInode
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationPutFileRevisionByInode(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationPutFileRevisionByInode) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationPutFileRevisionByInode
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationPutFileRevisionByInode) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Restore an older revision as the current revision for a path.
var (
	filesystemOperationRestoreRevisionFieldPath             = big.NewInt(1 << 0)
	filesystemOperationRestoreRevisionFieldSourceRevisionNo = big.NewInt(1 << 1)
)

type FilesystemOperationRestoreRevision struct {
	// Absolute path that must resolve to a visible file.
	Path AbsolutePath `json:"path" url:"path"`
	// Existing historical revision whose content will be copied into a new current revision.
	SourceRevisionNo RevisionNo `json:"source_revision_no" url:"source_revision_no"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationRestoreRevision) GetPath() AbsolutePath {
	if f == nil {
		return ""
	}
	return f.Path
}

func (f *FilesystemOperationRestoreRevision) GetSourceRevisionNo() RevisionNo {
	if f == nil {
		return 0
	}
	return f.SourceRevisionNo
}

func (f *FilesystemOperationRestoreRevision) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationRestoreRevision) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationRestoreRevision) SetPath(path AbsolutePath) {
	f.Path = path
	f.require(filesystemOperationRestoreRevisionFieldPath)
}

// SetSourceRevisionNo sets the SourceRevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationRestoreRevision) SetSourceRevisionNo(sourceRevisionNo RevisionNo) {
	f.SourceRevisionNo = sourceRevisionNo
	f.require(filesystemOperationRestoreRevisionFieldSourceRevisionNo)
}

func (f *FilesystemOperationRestoreRevision) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationRestoreRevision
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationRestoreRevision(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationRestoreRevision) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationRestoreRevision
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationRestoreRevision) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Restore a deleted file or subtree.
//
// `inode_id` and `deletion_seq` identify one exact deletion. A stale
// sequence returns `not_deleted` and cannot undo a later deletion.
var (
	filesystemOperationUndeleteFieldDeletionSeq = big.NewInt(1 << 0)
	filesystemOperationUndeleteFieldInodeID     = big.NewInt(1 << 1)
	filesystemOperationUndeleteFieldPath        = big.NewInt(1 << 2)
)

type FilesystemOperationUndelete struct {
	// Observed deletion sequence, which prevents cancelling a newer tombstone generation.
	DeletionSeq ChangeSeq `json:"deletion_seq" url:"deletion_seq"`
	// Stable inode ID within a namespace
	InodeID string `json:"inode_id" url:"inode_id"`
	// Optional destination for the restored inode.
	//
	// When absent, the inode is rebound to the parent and name recorded by the
	// deletion. Parent identity, rather than an old path string, keeps this
	// correct after ancestor renames. An explicit path is required when the
	// deletion recorded no binding.
	Path *AbsolutePath `json:"path,omitempty" url:"path,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationUndelete) GetDeletionSeq() ChangeSeq {
	if f == nil {
		return 0
	}
	return f.DeletionSeq
}

func (f *FilesystemOperationUndelete) GetInodeID() string {
	if f == nil {
		return ""
	}
	return f.InodeID
}

func (f *FilesystemOperationUndelete) GetPath() *AbsolutePath {
	if f == nil {
		return nil
	}
	return f.Path
}

func (f *FilesystemOperationUndelete) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationUndelete) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetDeletionSeq sets the DeletionSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationUndelete) SetDeletionSeq(deletionSeq ChangeSeq) {
	f.DeletionSeq = deletionSeq
	f.require(filesystemOperationUndeleteFieldDeletionSeq)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationUndelete) SetInodeID(inodeID string) {
	f.InodeID = inodeID
	f.require(filesystemOperationUndeleteFieldInodeID)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationUndelete) SetPath(path *AbsolutePath) {
	f.Path = path
	f.require(filesystemOperationUndeleteFieldPath)
}

func (f *FilesystemOperationUndelete) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationUndelete
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationUndelete(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationUndelete) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationUndelete
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationUndelete) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Write and remove attributes on the inode one path resolves to.
var (
	filesystemOperationUpdateAttributesFieldExpectedAttributesRevisionNo = big.NewInt(1 << 0)
	filesystemOperationUpdateAttributesFieldExpectedInodeID              = big.NewInt(1 << 1)
	filesystemOperationUpdateAttributesFieldPath                         = big.NewInt(1 << 2)
	filesystemOperationUpdateAttributesFieldRemove                       = big.NewInt(1 << 3)
	filesystemOperationUpdateAttributesFieldSet                          = big.NewInt(1 << 4)
)

type FilesystemOperationUpdateAttributes struct {
	// When set, the update applies only while the inode's attribute
	// revision is still this one. Absent means the update is applied
	// over whatever revision is current; either way the write carries
	// its own revision guard, so a concurrent update never merges
	// silently.
	ExpectedAttributesRevisionNo *AttributeRevisionNo `json:"expected_attributes_revision_no,omitempty" url:"expected_attributes_revision_no,omitempty"`
	// Stable inode ID within a namespace
	ExpectedInodeID *string `json:"expected_inode_id,omitempty" url:"expected_inode_id,omitempty"`
	// Absolute path that must resolve to a visible file or directory.
	Path AbsolutePath `json:"path" url:"path"`
	// Attribute keys to remove.
	//
	// A list preserves duplicate entries so validation can report them instead
	// of silently deduplicating the request.
	Remove []AttributeKey `json:"remove,omitempty" url:"remove,omitempty"`
	// Attributes to write. Each key replaces whatever the inode
	// currently holds under it; keys the inode holds and this map does
	// not name are left alone.
	Set map[string]AttributeValue `json:"set,omitempty" url:"set,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesystemOperationUpdateAttributes) GetExpectedAttributesRevisionNo() *AttributeRevisionNo {
	if f == nil {
		return nil
	}
	return f.ExpectedAttributesRevisionNo
}

func (f *FilesystemOperationUpdateAttributes) GetExpectedInodeID() *string {
	if f == nil {
		return nil
	}
	return f.ExpectedInodeID
}

func (f *FilesystemOperationUpdateAttributes) GetPath() AbsolutePath {
	if f == nil {
		return ""
	}
	return f.Path
}

func (f *FilesystemOperationUpdateAttributes) GetRemove() []AttributeKey {
	if f == nil {
		return nil
	}
	return f.Remove
}

func (f *FilesystemOperationUpdateAttributes) GetSet() map[string]AttributeValue {
	if f == nil {
		return nil
	}
	return f.Set
}

func (f *FilesystemOperationUpdateAttributes) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesystemOperationUpdateAttributes) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetExpectedAttributesRevisionNo sets the ExpectedAttributesRevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationUpdateAttributes) SetExpectedAttributesRevisionNo(expectedAttributesRevisionNo *AttributeRevisionNo) {
	f.ExpectedAttributesRevisionNo = expectedAttributesRevisionNo
	f.require(filesystemOperationUpdateAttributesFieldExpectedAttributesRevisionNo)
}

// SetExpectedInodeID sets the ExpectedInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationUpdateAttributes) SetExpectedInodeID(expectedInodeID *string) {
	f.ExpectedInodeID = expectedInodeID
	f.require(filesystemOperationUpdateAttributesFieldExpectedInodeID)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationUpdateAttributes) SetPath(path AbsolutePath) {
	f.Path = path
	f.require(filesystemOperationUpdateAttributesFieldPath)
}

// SetRemove sets the Remove field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationUpdateAttributes) SetRemove(remove []AttributeKey) {
	f.Remove = remove
	f.require(filesystemOperationUpdateAttributesFieldRemove)
}

// SetSet sets the Set field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesystemOperationUpdateAttributes) SetSet(set map[string]AttributeValue) {
	f.Set = set
	f.require(filesystemOperationUpdateAttributesFieldSet)
}

func (f *FilesystemOperationUpdateAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesystemOperationUpdateAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesystemOperationUpdateAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesystemOperationUpdateAttributes) MarshalJSON() ([]byte, error) {
	type embed FilesystemOperationUpdateAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesystemOperationUpdateAttributes) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}
