// Code generated by Fern. DO NOT EDIT.

package loonfs

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	getFileBytesRequestFieldNamespaceID = big.NewInt(1 << 0)
	getFileBytesRequestFieldPath        = big.NewInt(1 << 1)
	getFileBytesRequestFieldRevisionNo  = big.NewInt(1 << 2)
	getFileBytesRequestFieldSnapshotID  = big.NewInt(1 << 3)
)

type GetFileBytesRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Absolute file path
	Path string `json:"-" url:"path"`
	// Optional prior revision number; cannot be combined with snapshot_id
	RevisionNo *RevisionNo `json:"-" url:"revision_no,omitempty"`
	// Use the file revision captured by this snapshot
	SnapshotID *CheckpointID `json:"-" url:"snapshot_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFileBytesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileBytesRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(getFileBytesRequestFieldNamespaceID)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileBytesRequest) SetPath(path string) {
	g.Path = path
	g.require(getFileBytesRequestFieldPath)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileBytesRequest) SetRevisionNo(revisionNo *RevisionNo) {
	g.RevisionNo = revisionNo
	g.require(getFileBytesRequestFieldRevisionNo)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileBytesRequest) SetSnapshotID(snapshotID *CheckpointID) {
	g.SnapshotID = snapshotID
	g.require(getFileBytesRequestFieldSnapshotID)
}

var (
	beginDownloadRequestFieldNamespaceID = big.NewInt(1 << 0)
	beginDownloadRequestFieldSnapshotID  = big.NewInt(1 << 1)
	beginDownloadRequestFieldPath        = big.NewInt(1 << 2)
	beginDownloadRequestFieldRevisionNo  = big.NewInt(1 << 3)
)

type BeginDownloadRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Use the file revision captured by this snapshot
	SnapshotID *CheckpointID `json:"-" url:"snapshot_id,omitempty"`
	// Absolute path of the file to read.
	Path AbsolutePath `json:"path" url:"-"`
	// Revision to read, or `None` for the path's current revision.
	RevisionNo *RevisionNo `json:"revision_no,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BeginDownloadRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadRequest) SetNamespaceID(namespaceID string) {
	b.NamespaceID = namespaceID
	b.require(beginDownloadRequestFieldNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadRequest) SetSnapshotID(snapshotID *CheckpointID) {
	b.SnapshotID = snapshotID
	b.require(beginDownloadRequestFieldSnapshotID)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadRequest) SetPath(path AbsolutePath) {
	b.Path = path
	b.require(beginDownloadRequestFieldPath)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadRequest) SetRevisionNo(revisionNo *RevisionNo) {
	b.RevisionNo = revisionNo
	b.require(beginDownloadRequestFieldRevisionNo)
}

func (b *BeginDownloadRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler BeginDownloadRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*b = BeginDownloadRequest(body)
	return nil
}

func (b *BeginDownloadRequest) MarshalJSON() ([]byte, error) {
	type embed BeginDownloadRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	grepRequestFieldNamespaceID     = big.NewInt(1 << 0)
	grepRequestFieldPattern         = big.NewInt(1 << 1)
	grepRequestFieldCaseInsensitive = big.NewInt(1 << 2)
	grepRequestFieldPathPrefix      = big.NewInt(1 << 3)
	grepRequestFieldAllowScan       = big.NewInt(1 << 4)
	grepRequestFieldAllowStale      = big.NewInt(1 << 5)
	grepRequestFieldLimit           = big.NewInt(1 << 6)
	grepRequestFieldCursor          = big.NewInt(1 << 7)
)

type GrepRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Pattern in the Rust `regex` crate's dialect. Its UTF-8 encoding must be at most 1024 bytes.
	Pattern string `json:"-" url:"pattern"`
	// Match case-insensitively (`true` or `false`). Defaults to `false`.
	CaseInsensitive *bool `json:"-" url:"case_insensitive,omitempty"`
	// Complete absolute path used to restrict matches.
	PathPrefix *string `json:"-" url:"path_prefix,omitempty"`
	// Permit a capped exhaustive scan when the pattern has no required grams (`true` or `false`). Defaults to `false`.
	AllowScan *bool `json:"-" url:"allow_scan,omitempty"`
	// Return indexed-only results when the unindexed tail exceeds the scan budget (`true` or `false`). Defaults to `false`.
	AllowStale *bool `json:"-" url:"allow_stale,omitempty"`
	// Maximum matches per page
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque grep page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GrepRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(grepRequestFieldNamespaceID)
}

// SetPattern sets the Pattern field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetPattern(pattern string) {
	g.Pattern = pattern
	g.require(grepRequestFieldPattern)
}

// SetCaseInsensitive sets the CaseInsensitive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetCaseInsensitive(caseInsensitive *bool) {
	g.CaseInsensitive = caseInsensitive
	g.require(grepRequestFieldCaseInsensitive)
}

// SetPathPrefix sets the PathPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetPathPrefix(pathPrefix *string) {
	g.PathPrefix = pathPrefix
	g.require(grepRequestFieldPathPrefix)
}

// SetAllowScan sets the AllowScan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetAllowScan(allowScan *bool) {
	g.AllowScan = allowScan
	g.require(grepRequestFieldAllowScan)
}

// SetAllowStale sets the AllowStale field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetAllowStale(allowStale *bool) {
	g.AllowStale = allowStale
	g.require(grepRequestFieldAllowStale)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(grepRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(grepRequestFieldCursor)
}

var (
	listPathEntriesRequestFieldNamespaceID       = big.NewInt(1 << 0)
	listPathEntriesRequestFieldPath              = big.NewInt(1 << 1)
	listPathEntriesRequestFieldLimit             = big.NewInt(1 << 2)
	listPathEntriesRequestFieldCursor            = big.NewInt(1 << 3)
	listPathEntriesRequestFieldIncludeAttributes = big.NewInt(1 << 4)
	listPathEntriesRequestFieldSnapshotID        = big.NewInt(1 << 5)
)

type ListPathEntriesRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Absolute filesystem path
	Path string `json:"-" url:"path"`
	// Maximum page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque directory-list page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Project each entry's attribute map and revision (`true` or `false`). Defaults to `false`: a page holds many entries and each map may be 64 KiB, so a listing does not carry them unless asked.
	IncludeAttributes *bool `json:"-" url:"include_attributes,omitempty"`
	// Use the directory state captured by this snapshot
	SnapshotID *CheckpointID `json:"-" url:"snapshot_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListPathEntriesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesRequest) SetNamespaceID(namespaceID string) {
	l.NamespaceID = namespaceID
	l.require(listPathEntriesRequestFieldNamespaceID)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesRequest) SetPath(path string) {
	l.Path = path
	l.require(listPathEntriesRequestFieldPath)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listPathEntriesRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listPathEntriesRequestFieldCursor)
}

// SetIncludeAttributes sets the IncludeAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesRequest) SetIncludeAttributes(includeAttributes *bool) {
	l.IncludeAttributes = includeAttributes
	l.require(listPathEntriesRequestFieldIncludeAttributes)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesRequest) SetSnapshotID(snapshotID *CheckpointID) {
	l.SnapshotID = snapshotID
	l.require(listPathEntriesRequestFieldSnapshotID)
}

var (
	listFileRevisionsRequestFieldNamespaceID = big.NewInt(1 << 0)
	listFileRevisionsRequestFieldPath        = big.NewInt(1 << 1)
	listFileRevisionsRequestFieldLimit       = big.NewInt(1 << 2)
	listFileRevisionsRequestFieldCursor      = big.NewInt(1 << 3)
)

type ListFileRevisionsRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Absolute file path
	Path string `json:"-" url:"path"`
	// Maximum page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque file-revisions page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFileRevisionsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsRequest) SetNamespaceID(namespaceID string) {
	l.NamespaceID = namespaceID
	l.require(listFileRevisionsRequestFieldNamespaceID)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsRequest) SetPath(path string) {
	l.Path = path
	l.require(listFileRevisionsRequestFieldPath)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFileRevisionsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listFileRevisionsRequestFieldCursor)
}

var (
	getPathEntryRequestFieldNamespaceID       = big.NewInt(1 << 0)
	getPathEntryRequestFieldPath              = big.NewInt(1 << 1)
	getPathEntryRequestFieldIncludeAttributes = big.NewInt(1 << 2)
	getPathEntryRequestFieldSnapshotID        = big.NewInt(1 << 3)
)

type GetPathEntryRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Absolute filesystem path
	Path string `json:"-" url:"path"`
	// Project the inode's attribute map and revision (`true` or `false`). Defaults to `true`: a stat answers for one path and a map is capped at 64 KiB.
	IncludeAttributes *bool `json:"-" url:"include_attributes,omitempty"`
	// Use the path state captured by this snapshot
	SnapshotID *CheckpointID `json:"-" url:"snapshot_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPathEntryRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPathEntryRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(getPathEntryRequestFieldNamespaceID)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPathEntryRequest) SetPath(path string) {
	g.Path = path
	g.require(getPathEntryRequestFieldPath)
}

// SetIncludeAttributes sets the IncludeAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPathEntryRequest) SetIncludeAttributes(includeAttributes *bool) {
	g.IncludeAttributes = includeAttributes
	g.require(getPathEntryRequestFieldIncludeAttributes)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPathEntryRequest) SetSnapshotID(snapshotID *CheckpointID) {
	g.SnapshotID = snapshotID
	g.require(getPathEntryRequestFieldSnapshotID)
}

// A short-lived capability to read one file's content object, plus
// everything the reader needs to check what arrives.
//
// The raw object key is deliberately not here, exactly as it is not in a
// `direct_put` grant: a client learns a URL that expires, not an address it
// can revisit.
//
// The grant names one immutable content object, so it does not go stale
// when the path moves on. A commit that replaces the file writes a new
// object and leaves this one alone; what the capability reads is what the
// requested revision held when the grant was issued, and the reference
// says which bytes those are.
var (
	beginDownloadResponseFieldAccess      = big.NewInt(1 << 0)
	beginDownloadResponseFieldContentRef  = big.NewInt(1 << 1)
	beginDownloadResponseFieldNamespaceID = big.NewInt(1 << 2)
	beginDownloadResponseFieldPath        = big.NewInt(1 << 3)
	beginDownloadResponseFieldRevisionNo  = big.NewInt(1 << 4)
)

type BeginDownloadResponse struct {
	// Short-lived read capability the client uses without learning the raw object key.
	Access *ObjectTransferAccess `json:"access" url:"access"`
	// Identity, byte length, and checksum evidence for the object the
	// capability reads. A reader checks the bytes it receives against
	// `size_bytes` and recomputes `checksum.algorithm` over the complete
	// payload.
	ContentRef *ContentRef `json:"content_ref" url:"content_ref"`
	// Namespace that was read.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Absolute path as rendered from stored display names.
	Path AbsolutePath `json:"path" url:"path"`
	// Revision the capability reads, resolved from the request.
	RevisionNo RevisionNo `json:"revision_no" url:"revision_no"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BeginDownloadResponse) GetAccess() *ObjectTransferAccess {
	if b == nil {
		return nil
	}
	return b.Access
}

func (b *BeginDownloadResponse) GetContentRef() *ContentRef {
	if b == nil {
		return nil
	}
	return b.ContentRef
}

func (b *BeginDownloadResponse) GetNamespaceID() NamespaceID {
	if b == nil {
		return ""
	}
	return b.NamespaceID
}

func (b *BeginDownloadResponse) GetPath() AbsolutePath {
	if b == nil {
		return ""
	}
	return b.Path
}

func (b *BeginDownloadResponse) GetRevisionNo() RevisionNo {
	if b == nil {
		return 0
	}
	return b.RevisionNo
}

func (b *BeginDownloadResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BeginDownloadResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetAccess sets the Access field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadResponse) SetAccess(access *ObjectTransferAccess) {
	b.Access = access
	b.require(beginDownloadResponseFieldAccess)
}

// SetContentRef sets the ContentRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadResponse) SetContentRef(contentRef *ContentRef) {
	b.ContentRef = contentRef
	b.require(beginDownloadResponseFieldContentRef)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadResponse) SetNamespaceID(namespaceID NamespaceID) {
	b.NamespaceID = namespaceID
	b.require(beginDownloadResponseFieldNamespaceID)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadResponse) SetPath(path AbsolutePath) {
	b.Path = path
	b.require(beginDownloadResponseFieldPath)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadResponse) SetRevisionNo(revisionNo RevisionNo) {
	b.RevisionNo = revisionNo
	b.require(beginDownloadResponseFieldRevisionNo)
}

func (b *BeginDownloadResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BeginDownloadResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BeginDownloadResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BeginDownloadResponse) MarshalJSON() ([]byte, error) {
	type embed BeginDownloadResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BeginDownloadResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

// One line-oriented match.
var (
	grepMatchFieldByteOffset    = big.NewInt(1 << 0)
	grepMatchFieldInodeID       = big.NewInt(1 << 1)
	grepMatchFieldLine          = big.NewInt(1 << 2)
	grepMatchFieldLineNumber    = big.NewInt(1 << 3)
	grepMatchFieldLineTruncated = big.NewInt(1 << 4)
	grepMatchFieldPath          = big.NewInt(1 << 5)
	grepMatchFieldRevisionNo    = big.NewInt(1 << 6)
)

type GrepMatch struct {
	// Byte offset of the match within the file.
	ByteOffset int64 `json:"byte_offset" url:"byte_offset"`
	// Stable inode ID within a namespace
	InodeID string `json:"inode_id" url:"inode_id"`
	// The matching line, truncated to the server's line cap.
	Line string `json:"line" url:"line"`
	// One-based line number of the match.
	LineNumber int64 `json:"line_number" url:"line_number"`
	// True when `line` was truncated.
	LineTruncated bool `json:"line_truncated" url:"line_truncated"`
	// The file's absolute path, derived at the snapshot.
	Path AbsolutePath `json:"path" url:"path"`
	// The matched revision (the newest visible one at the snapshot).
	RevisionNo RevisionNo `json:"revision_no" url:"revision_no"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GrepMatch) GetByteOffset() int64 {
	if g == nil {
		return 0
	}
	return g.ByteOffset
}

func (g *GrepMatch) GetInodeID() string {
	if g == nil {
		return ""
	}
	return g.InodeID
}

func (g *GrepMatch) GetLine() string {
	if g == nil {
		return ""
	}
	return g.Line
}

func (g *GrepMatch) GetLineNumber() int64 {
	if g == nil {
		return 0
	}
	return g.LineNumber
}

func (g *GrepMatch) GetLineTruncated() bool {
	if g == nil {
		return false
	}
	return g.LineTruncated
}

func (g *GrepMatch) GetPath() AbsolutePath {
	if g == nil {
		return ""
	}
	return g.Path
}

func (g *GrepMatch) GetRevisionNo() RevisionNo {
	if g == nil {
		return 0
	}
	return g.RevisionNo
}

func (g *GrepMatch) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GrepMatch) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetByteOffset sets the ByteOffset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetByteOffset(byteOffset int64) {
	g.ByteOffset = byteOffset
	g.require(grepMatchFieldByteOffset)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetInodeID(inodeID string) {
	g.InodeID = inodeID
	g.require(grepMatchFieldInodeID)
}

// SetLine sets the Line field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetLine(line string) {
	g.Line = line
	g.require(grepMatchFieldLine)
}

// SetLineNumber sets the LineNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetLineNumber(lineNumber int64) {
	g.LineNumber = lineNumber
	g.require(grepMatchFieldLineNumber)
}

// SetLineTruncated sets the LineTruncated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetLineTruncated(lineTruncated bool) {
	g.LineTruncated = lineTruncated
	g.require(grepMatchFieldLineTruncated)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetPath(path AbsolutePath) {
	g.Path = path
	g.require(grepMatchFieldPath)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetRevisionNo(revisionNo RevisionNo) {
	g.RevisionNo = revisionNo
	g.require(grepMatchFieldRevisionNo)
}

func (g *GrepMatch) UnmarshalJSON(data []byte) error {
	type unmarshaler GrepMatch
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GrepMatch(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GrepMatch) MarshalJSON() ([]byte, error) {
	type embed GrepMatch
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GrepMatch) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// One content-search page.
var (
	grepResponseFieldBuiltThroughSeq = big.NewInt(1 << 0)
	grepResponseFieldHeadSeq         = big.NewInt(1 << 1)
	grepResponseFieldMatches         = big.NewInt(1 << 2)
	grepResponseFieldNamespaceID     = big.NewInt(1 << 3)
	grepResponseFieldNextCursor      = big.NewInt(1 << 4)
	grepResponseFieldTailScanned     = big.NewInt(1 << 5)
)

type GrepResponse struct {
	// Commits at or below this sequence were answered from the index.
	BuiltThroughSeq ChangeSeq `json:"built_through_seq" url:"built_through_seq"`
	// Sequence this page was evaluated at. Pages are evaluated against
	// the namespace head at page time; the cursor is an ordering resume,
	// not a snapshot pin.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Matches in ascending `(inode_id, byte_offset)` order. A page may
	// return fewer matches than its limit and still carry a cursor: the
	// per-page verified-candidate budget bounds how much content one
	// request reads, whatever the plan's false-positive rate.
	Matches []*GrepMatch `json:"matches" url:"matches"`
	// Namespace searched.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Present when another page follows.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// True when revisions after `built_through_seq` were scanned
	// exhaustively; false only when `allow_stale` skipped them.
	TailScanned bool `json:"tail_scanned" url:"tail_scanned"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GrepResponse) GetBuiltThroughSeq() ChangeSeq {
	if g == nil {
		return 0
	}
	return g.BuiltThroughSeq
}

func (g *GrepResponse) GetHeadSeq() ChangeSeq {
	if g == nil {
		return 0
	}
	return g.HeadSeq
}

func (g *GrepResponse) GetMatches() []*GrepMatch {
	if g == nil {
		return nil
	}
	return g.Matches
}

func (g *GrepResponse) GetNamespaceID() NamespaceID {
	if g == nil {
		return ""
	}
	return g.NamespaceID
}

func (g *GrepResponse) GetNextCursor() *string {
	if g == nil {
		return nil
	}
	return g.NextCursor
}

func (g *GrepResponse) GetTailScanned() bool {
	if g == nil {
		return false
	}
	return g.TailScanned
}

func (g *GrepResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GrepResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBuiltThroughSeq sets the BuiltThroughSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetBuiltThroughSeq(builtThroughSeq ChangeSeq) {
	g.BuiltThroughSeq = builtThroughSeq
	g.require(grepResponseFieldBuiltThroughSeq)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetHeadSeq(headSeq ChangeSeq) {
	g.HeadSeq = headSeq
	g.require(grepResponseFieldHeadSeq)
}

// SetMatches sets the Matches field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetMatches(matches []*GrepMatch) {
	g.Matches = matches
	g.require(grepResponseFieldMatches)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetNamespaceID(namespaceID NamespaceID) {
	g.NamespaceID = namespaceID
	g.require(grepResponseFieldNamespaceID)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetNextCursor(nextCursor *string) {
	g.NextCursor = nextCursor
	g.require(grepResponseFieldNextCursor)
}

// SetTailScanned sets the TailScanned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetTailScanned(tailScanned bool) {
	g.TailScanned = tailScanned
	g.require(grepResponseFieldTailScanned)
}

func (g *GrepResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GrepResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GrepResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GrepResponse) MarshalJSON() ([]byte, error) {
	type embed GrepResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GrepResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// One directory listing and the namespace head it was answered at.
//
// The envelope names the listing target and head so an empty directory
// still tells the caller which state it observed, and so the response can
// grow without reshaping `entries`.
var (
	listPathEntriesResponseFieldEntries     = big.NewInt(1 << 0)
	listPathEntriesResponseFieldHeadSeq     = big.NewInt(1 << 1)
	listPathEntriesResponseFieldNamespaceID = big.NewInt(1 << 2)
	listPathEntriesResponseFieldNextCursor  = big.NewInt(1 << 3)
	listPathEntriesResponseFieldPath        = big.NewInt(1 << 4)
)

type ListPathEntriesResponse struct {
	// Directory entries for this page.
	//
	// Entries are returned in canonical name-key order. Higher-level display
	// surfaces may sort entries separately for presentation.
	Entries []*PathEntry `json:"entries" url:"entries"`
	// Namespace head sequence this listing was read from.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Namespace that was read.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Cursor for the next page, if more entries remain.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// Absolute path of the listed directory.
	Path AbsolutePath `json:"path" url:"path"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPathEntriesResponse) GetEntries() []*PathEntry {
	if l == nil {
		return nil
	}
	return l.Entries
}

func (l *ListPathEntriesResponse) GetHeadSeq() ChangeSeq {
	if l == nil {
		return 0
	}
	return l.HeadSeq
}

func (l *ListPathEntriesResponse) GetNamespaceID() NamespaceID {
	if l == nil {
		return ""
	}
	return l.NamespaceID
}

func (l *ListPathEntriesResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListPathEntriesResponse) GetPath() AbsolutePath {
	if l == nil {
		return ""
	}
	return l.Path
}

func (l *ListPathEntriesResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListPathEntriesResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetEntries sets the Entries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesResponse) SetEntries(entries []*PathEntry) {
	l.Entries = entries
	l.require(listPathEntriesResponseFieldEntries)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesResponse) SetHeadSeq(headSeq ChangeSeq) {
	l.HeadSeq = headSeq
	l.require(listPathEntriesResponseFieldHeadSeq)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesResponse) SetNamespaceID(namespaceID NamespaceID) {
	l.NamespaceID = namespaceID
	l.require(listPathEntriesResponseFieldNamespaceID)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesResponse) SetNextCursor(nextCursor *string) {
	l.NextCursor = nextCursor
	l.require(listPathEntriesResponseFieldNextCursor)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPathEntriesResponse) SetPath(path AbsolutePath) {
	l.Path = path
	l.require(listPathEntriesResponseFieldPath)
}

func (l *ListPathEntriesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPathEntriesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPathEntriesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPathEntriesResponse) MarshalJSON() ([]byte, error) {
	type embed ListPathEntriesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPathEntriesResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
