// Code generated by Fern. DO NOT EDIT.

package loonfs

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	beginDownloadByInodeBodyFieldNamespaceID = big.NewInt(1 << 0)
	beginDownloadByInodeBodyFieldInodeID     = big.NewInt(1 << 1)
	beginDownloadByInodeBodyFieldRevisionNo  = big.NewInt(1 << 2)
)

type BeginDownloadByInodeBody struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// File inode ID
	InodeID string `json:"-" url:"-"`
	// Revision number
	RevisionNo RevisionNo                  `json:"-" url:"-"`
	Body       BeginDownloadByInodeRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BeginDownloadByInodeBody) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeBody) SetNamespaceID(namespaceID string) {
	b.NamespaceID = namespaceID
	b.require(beginDownloadByInodeBodyFieldNamespaceID)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeBody) SetInodeID(inodeID string) {
	b.InodeID = inodeID
	b.require(beginDownloadByInodeBodyFieldInodeID)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeBody) SetRevisionNo(revisionNo RevisionNo) {
	b.RevisionNo = revisionNo
	b.require(beginDownloadByInodeBodyFieldRevisionNo)
}

func (b *BeginDownloadByInodeBody) UnmarshalJSON(data []byte) error {
	var body BeginDownloadByInodeRequest
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.Body = body
	return nil
}

func (b *BeginDownloadByInodeBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

var (
	getFileRevisionBytesByInodeRequestFieldNamespaceID = big.NewInt(1 << 0)
	getFileRevisionBytesByInodeRequestFieldInodeID     = big.NewInt(1 << 1)
	getFileRevisionBytesByInodeRequestFieldRevisionNo  = big.NewInt(1 << 2)
)

type GetFileRevisionBytesByInodeRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// File inode ID
	InodeID string `json:"-" url:"-"`
	// Revision number
	RevisionNo RevisionNo `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFileRevisionBytesByInodeRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileRevisionBytesByInodeRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(getFileRevisionBytesByInodeRequestFieldNamespaceID)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileRevisionBytesByInodeRequest) SetInodeID(inodeID string) {
	g.InodeID = inodeID
	g.require(getFileRevisionBytesByInodeRequestFieldInodeID)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileRevisionBytesByInodeRequest) SetRevisionNo(revisionNo RevisionNo) {
	g.RevisionNo = revisionNo
	g.require(getFileRevisionBytesByInodeRequestFieldRevisionNo)
}

var (
	listFileRevisionsByInodeRequestFieldNamespaceID = big.NewInt(1 << 0)
	listFileRevisionsByInodeRequestFieldInodeID     = big.NewInt(1 << 1)
	listFileRevisionsByInodeRequestFieldLimit       = big.NewInt(1 << 2)
	listFileRevisionsByInodeRequestFieldCursor      = big.NewInt(1 << 3)
)

type ListFileRevisionsByInodeRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// File inode ID
	InodeID string `json:"-" url:"-"`
	// Maximum page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque file-revisions page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFileRevisionsByInodeRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsByInodeRequest) SetNamespaceID(namespaceID string) {
	l.NamespaceID = namespaceID
	l.require(listFileRevisionsByInodeRequestFieldNamespaceID)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsByInodeRequest) SetInodeID(inodeID string) {
	l.InodeID = inodeID
	l.require(listFileRevisionsByInodeRequestFieldInodeID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsByInodeRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFileRevisionsByInodeRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsByInodeRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listFileRevisionsByInodeRequestFieldCursor)
}

var (
	statInodeRequestFieldNamespaceID       = big.NewInt(1 << 0)
	statInodeRequestFieldInodeID           = big.NewInt(1 << 1)
	statInodeRequestFieldIncludeAttributes = big.NewInt(1 << 2)
)

type StatInodeRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Inode ID
	InodeID string `json:"-" url:"-"`
	// Project the inode's attribute map and revision (`true` or `false`). Defaults to `true`: a stat answers for one path and a map is capped at 64 KiB.
	IncludeAttributes *bool `json:"-" url:"include_attributes,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StatInodeRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StatInodeRequest) SetNamespaceID(namespaceID string) {
	s.NamespaceID = namespaceID
	s.require(statInodeRequestFieldNamespaceID)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StatInodeRequest) SetInodeID(inodeID string) {
	s.InodeID = inodeID
	s.require(statInodeRequestFieldInodeID)
}

// SetIncludeAttributes sets the IncludeAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StatInodeRequest) SetIncludeAttributes(includeAttributes *bool) {
	s.IncludeAttributes = includeAttributes
	s.require(statInodeRequestFieldIncludeAttributes)
}

// Empty request for an inode-addressed download.
type BeginDownloadByInodeRequest = map[string]any

// A short-lived capability to read one inode revision.
var (
	beginDownloadByInodeResponseFieldAccess      = big.NewInt(1 << 0)
	beginDownloadByInodeResponseFieldContentRef  = big.NewInt(1 << 1)
	beginDownloadByInodeResponseFieldInodeID     = big.NewInt(1 << 2)
	beginDownloadByInodeResponseFieldNamespaceID = big.NewInt(1 << 3)
	beginDownloadByInodeResponseFieldRevisionNo  = big.NewInt(1 << 4)
)

type BeginDownloadByInodeResponse struct {
	// Short-lived provider access without the raw object key.
	Access *ObjectTransferAccess `json:"access" url:"access"`
	// Content identity, size, and checksum.
	ContentRef *ContentRef `json:"content_ref" url:"content_ref"`
	// Stable inode ID within a namespace
	InodeID string `json:"inode_id" url:"inode_id"`
	// Namespace that was read.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Revision being read.
	RevisionNo RevisionNo `json:"revision_no" url:"revision_no"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BeginDownloadByInodeResponse) GetAccess() *ObjectTransferAccess {
	if b == nil {
		return nil
	}
	return b.Access
}

func (b *BeginDownloadByInodeResponse) GetContentRef() *ContentRef {
	if b == nil {
		return nil
	}
	return b.ContentRef
}

func (b *BeginDownloadByInodeResponse) GetInodeID() string {
	if b == nil {
		return ""
	}
	return b.InodeID
}

func (b *BeginDownloadByInodeResponse) GetNamespaceID() NamespaceID {
	if b == nil {
		return ""
	}
	return b.NamespaceID
}

func (b *BeginDownloadByInodeResponse) GetRevisionNo() RevisionNo {
	if b == nil {
		return 0
	}
	return b.RevisionNo
}

func (b *BeginDownloadByInodeResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BeginDownloadByInodeResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetAccess sets the Access field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetAccess(access *ObjectTransferAccess) {
	b.Access = access
	b.require(beginDownloadByInodeResponseFieldAccess)
}

// SetContentRef sets the ContentRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetContentRef(contentRef *ContentRef) {
	b.ContentRef = contentRef
	b.require(beginDownloadByInodeResponseFieldContentRef)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetInodeID(inodeID string) {
	b.InodeID = inodeID
	b.require(beginDownloadByInodeResponseFieldInodeID)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetNamespaceID(namespaceID NamespaceID) {
	b.NamespaceID = namespaceID
	b.require(beginDownloadByInodeResponseFieldNamespaceID)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetRevisionNo(revisionNo RevisionNo) {
	b.RevisionNo = revisionNo
	b.require(beginDownloadByInodeResponseFieldRevisionNo)
}

func (b *BeginDownloadByInodeResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BeginDownloadByInodeResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BeginDownloadByInodeResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BeginDownloadByInodeResponse) MarshalJSON() ([]byte, error) {
	type embed BeginDownloadByInodeResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BeginDownloadByInodeResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}
