// Code generated by Fern. DO NOT EDIT.

package loonfs

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	getFileRevisionBytesByInodeRequestFieldNamespaceID = big.NewInt(1 << 0)
	getFileRevisionBytesByInodeRequestFieldInodeID     = big.NewInt(1 << 1)
	getFileRevisionBytesByInodeRequestFieldRevisionNo  = big.NewInt(1 << 2)
)

type GetFileRevisionBytesByInodeRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// File inode ID
	InodeID string `json:"-" url:"-"`
	// Revision number
	RevisionNo RevisionNo `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFileRevisionBytesByInodeRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileRevisionBytesByInodeRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(getFileRevisionBytesByInodeRequestFieldNamespaceID)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileRevisionBytesByInodeRequest) SetInodeID(inodeID string) {
	g.InodeID = inodeID
	g.require(getFileRevisionBytesByInodeRequestFieldInodeID)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileRevisionBytesByInodeRequest) SetRevisionNo(revisionNo RevisionNo) {
	g.RevisionNo = revisionNo
	g.require(getFileRevisionBytesByInodeRequestFieldRevisionNo)
}

var (
	createDownloadByInodeRequestFieldNamespaceID = big.NewInt(1 << 0)
	createDownloadByInodeRequestFieldInodeID     = big.NewInt(1 << 1)
	createDownloadByInodeRequestFieldRevisionNo  = big.NewInt(1 << 2)
)

type CreateDownloadByInodeRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// File inode ID
	InodeID string `json:"-" url:"-"`
	// Revision number
	RevisionNo RevisionNo                  `json:"-" url:"-"`
	Body       BeginDownloadByInodeRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateDownloadByInodeRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDownloadByInodeRequest) SetNamespaceID(namespaceID string) {
	c.NamespaceID = namespaceID
	c.require(createDownloadByInodeRequestFieldNamespaceID)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDownloadByInodeRequest) SetInodeID(inodeID string) {
	c.InodeID = inodeID
	c.require(createDownloadByInodeRequestFieldInodeID)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDownloadByInodeRequest) SetRevisionNo(revisionNo RevisionNo) {
	c.RevisionNo = revisionNo
	c.require(createDownloadByInodeRequestFieldRevisionNo)
}

func (c *CreateDownloadByInodeRequest) UnmarshalJSON(data []byte) error {
	var body BeginDownloadByInodeRequest
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateDownloadByInodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	listInodeChildrenRequestFieldNamespaceID       = big.NewInt(1 << 0)
	listInodeChildrenRequestFieldInodeID           = big.NewInt(1 << 1)
	listInodeChildrenRequestFieldLimit             = big.NewInt(1 << 2)
	listInodeChildrenRequestFieldCursor            = big.NewInt(1 << 3)
	listInodeChildrenRequestFieldIncludeAttributes = big.NewInt(1 << 4)
)

type ListInodeChildrenRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Directory inode ID
	InodeID string `json:"-" url:"-"`
	// Maximum page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque directory page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Project each entry's attribute map and revision (`true` or `false`). Defaults to `false`: a page holds many entries and each map may be 64 KiB, so a listing does not carry them unless asked.
	IncludeAttributes *bool `json:"-" url:"include_attributes,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListInodeChildrenRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenRequest) SetNamespaceID(namespaceID string) {
	l.NamespaceID = namespaceID
	l.require(listInodeChildrenRequestFieldNamespaceID)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenRequest) SetInodeID(inodeID string) {
	l.InodeID = inodeID
	l.require(listInodeChildrenRequestFieldInodeID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listInodeChildrenRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listInodeChildrenRequestFieldCursor)
}

// SetIncludeAttributes sets the IncludeAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenRequest) SetIncludeAttributes(includeAttributes *bool) {
	l.IncludeAttributes = includeAttributes
	l.require(listInodeChildrenRequestFieldIncludeAttributes)
}

var (
	listFileRevisionsByInodeRequestFieldNamespaceID = big.NewInt(1 << 0)
	listFileRevisionsByInodeRequestFieldInodeID     = big.NewInt(1 << 1)
	listFileRevisionsByInodeRequestFieldLimit       = big.NewInt(1 << 2)
	listFileRevisionsByInodeRequestFieldCursor      = big.NewInt(1 << 3)
)

type ListFileRevisionsByInodeRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// File inode ID
	InodeID string `json:"-" url:"-"`
	// Maximum page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque file-revisions page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFileRevisionsByInodeRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsByInodeRequest) SetNamespaceID(namespaceID string) {
	l.NamespaceID = namespaceID
	l.require(listFileRevisionsByInodeRequestFieldNamespaceID)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsByInodeRequest) SetInodeID(inodeID string) {
	l.InodeID = inodeID
	l.require(listFileRevisionsByInodeRequestFieldInodeID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsByInodeRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFileRevisionsByInodeRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFileRevisionsByInodeRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listFileRevisionsByInodeRequestFieldCursor)
}

var (
	getInodeRequestFieldNamespaceID       = big.NewInt(1 << 0)
	getInodeRequestFieldInodeID           = big.NewInt(1 << 1)
	getInodeRequestFieldIncludeAttributes = big.NewInt(1 << 2)
)

type GetInodeRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Inode ID
	InodeID string `json:"-" url:"-"`
	// Project the inode's attribute map and revision (`true` or `false`). Defaults to `true`: a stat answers for one path and a map is capped at 64 KiB.
	IncludeAttributes *bool `json:"-" url:"include_attributes,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetInodeRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetInodeRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(getInodeRequestFieldNamespaceID)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetInodeRequest) SetInodeID(inodeID string) {
	g.InodeID = inodeID
	g.require(getInodeRequestFieldInodeID)
}

// SetIncludeAttributes sets the IncludeAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetInodeRequest) SetIncludeAttributes(includeAttributes *bool) {
	g.IncludeAttributes = includeAttributes
	g.require(getInodeRequestFieldIncludeAttributes)
}

// Empty request for an inode-addressed download.
type BeginDownloadByInodeRequest = map[string]any

// A short-lived capability to read one inode revision.
var (
	beginDownloadByInodeResponseFieldAccess      = big.NewInt(1 << 0)
	beginDownloadByInodeResponseFieldContentRef  = big.NewInt(1 << 1)
	beginDownloadByInodeResponseFieldInodeID     = big.NewInt(1 << 2)
	beginDownloadByInodeResponseFieldNamespaceID = big.NewInt(1 << 3)
	beginDownloadByInodeResponseFieldRevisionNo  = big.NewInt(1 << 4)
)

type BeginDownloadByInodeResponse struct {
	// Short-lived provider access without the raw object key.
	Access *ObjectTransferAccess `json:"access" url:"access"`
	// Content identity, size, and checksum.
	ContentRef *ContentRef `json:"content_ref" url:"content_ref"`
	// Stable inode ID within a namespace
	InodeID string `json:"inode_id" url:"inode_id"`
	// Namespace that was read.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Revision being read.
	RevisionNo RevisionNo `json:"revision_no" url:"revision_no"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BeginDownloadByInodeResponse) GetAccess() *ObjectTransferAccess {
	if b == nil {
		return nil
	}
	return b.Access
}

func (b *BeginDownloadByInodeResponse) GetContentRef() *ContentRef {
	if b == nil {
		return nil
	}
	return b.ContentRef
}

func (b *BeginDownloadByInodeResponse) GetInodeID() string {
	if b == nil {
		return ""
	}
	return b.InodeID
}

func (b *BeginDownloadByInodeResponse) GetNamespaceID() NamespaceID {
	if b == nil {
		return ""
	}
	return b.NamespaceID
}

func (b *BeginDownloadByInodeResponse) GetRevisionNo() RevisionNo {
	if b == nil {
		return 0
	}
	return b.RevisionNo
}

func (b *BeginDownloadByInodeResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BeginDownloadByInodeResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetAccess sets the Access field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetAccess(access *ObjectTransferAccess) {
	b.Access = access
	b.require(beginDownloadByInodeResponseFieldAccess)
}

// SetContentRef sets the ContentRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetContentRef(contentRef *ContentRef) {
	b.ContentRef = contentRef
	b.require(beginDownloadByInodeResponseFieldContentRef)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetInodeID(inodeID string) {
	b.InodeID = inodeID
	b.require(beginDownloadByInodeResponseFieldInodeID)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetNamespaceID(namespaceID NamespaceID) {
	b.NamespaceID = namespaceID
	b.require(beginDownloadByInodeResponseFieldNamespaceID)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BeginDownloadByInodeResponse) SetRevisionNo(revisionNo RevisionNo) {
	b.RevisionNo = revisionNo
	b.require(beginDownloadByInodeResponseFieldRevisionNo)
}

func (b *BeginDownloadByInodeResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BeginDownloadByInodeResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BeginDownloadByInodeResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BeginDownloadByInodeResponse) MarshalJSON() ([]byte, error) {
	type embed BeginDownloadByInodeResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BeginDownloadByInodeResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

// One directory listing addressed by parent inode, and the namespace head
// it was answered at.
//
// The envelope names the parent by its stable inode identity rather than a
// path, so a page and its resumption always describe the same directory
// even when the parent is concurrently renamed or moved.
var (
	listInodeChildrenResponseFieldEntries       = big.NewInt(1 << 0)
	listInodeChildrenResponseFieldHeadSeq       = big.NewInt(1 << 1)
	listInodeChildrenResponseFieldNamespaceID   = big.NewInt(1 << 2)
	listInodeChildrenResponseFieldNextCursor    = big.NewInt(1 << 3)
	listInodeChildrenResponseFieldParentInodeID = big.NewInt(1 << 4)
)

type ListInodeChildrenResponse struct {
	// Directory entries for this page.
	//
	// Entries are returned in canonical name-key order. Higher-level display
	// surfaces may sort entries separately for presentation.
	Entries []*PathEntry `json:"entries" url:"entries"`
	// Namespace head sequence this listing was read from.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Namespace that was read.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Cursor for the next page, if more entries remain.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// Stable inode ID within a namespace
	ParentInodeID string `json:"parent_inode_id" url:"parent_inode_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListInodeChildrenResponse) GetEntries() []*PathEntry {
	if l == nil {
		return nil
	}
	return l.Entries
}

func (l *ListInodeChildrenResponse) GetHeadSeq() ChangeSeq {
	if l == nil {
		return 0
	}
	return l.HeadSeq
}

func (l *ListInodeChildrenResponse) GetNamespaceID() NamespaceID {
	if l == nil {
		return ""
	}
	return l.NamespaceID
}

func (l *ListInodeChildrenResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListInodeChildrenResponse) GetParentInodeID() string {
	if l == nil {
		return ""
	}
	return l.ParentInodeID
}

func (l *ListInodeChildrenResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListInodeChildrenResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetEntries sets the Entries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenResponse) SetEntries(entries []*PathEntry) {
	l.Entries = entries
	l.require(listInodeChildrenResponseFieldEntries)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenResponse) SetHeadSeq(headSeq ChangeSeq) {
	l.HeadSeq = headSeq
	l.require(listInodeChildrenResponseFieldHeadSeq)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenResponse) SetNamespaceID(namespaceID NamespaceID) {
	l.NamespaceID = namespaceID
	l.require(listInodeChildrenResponseFieldNamespaceID)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenResponse) SetNextCursor(nextCursor *string) {
	l.NextCursor = nextCursor
	l.require(listInodeChildrenResponseFieldNextCursor)
}

// SetParentInodeID sets the ParentInodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInodeChildrenResponse) SetParentInodeID(parentInodeID string) {
	l.ParentInodeID = parentInodeID
	l.require(listInodeChildrenResponseFieldParentInodeID)
}

func (l *ListInodeChildrenResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListInodeChildrenResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListInodeChildrenResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListInodeChildrenResponse) MarshalJSON() ([]byte, error) {
	type embed ListInodeChildrenResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListInodeChildrenResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
