// Code generated by Fern. DO NOT EDIT.

package loonfs

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	createNamespaceRequestFieldAccess      = big.NewInt(1 << 0)
	createNamespaceRequestFieldNamespaceID = big.NewInt(1 << 1)
)

type CreateNamespaceRequest struct {
	// The access mode, fixed for the namespace's life. Defaults to
	// unrestricted.
	Access *NamespaceAccess `json:"access,omitempty" url:"-"`
	// Durable namespace id to create.
	NamespaceID NamespaceID `json:"namespace_id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateNamespaceRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccess sets the Access field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNamespaceRequest) SetAccess(access *NamespaceAccess) {
	c.Access = access
	c.require(createNamespaceRequestFieldAccess)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNamespaceRequest) SetNamespaceID(namespaceID NamespaceID) {
	c.NamespaceID = namespaceID
	c.require(createNamespaceRequestFieldNamespaceID)
}

func (c *CreateNamespaceRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateNamespaceRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateNamespaceRequest(body)
	return nil
}

func (c *CreateNamespaceRequest) MarshalJSON() ([]byte, error) {
	type embed CreateNamespaceRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteNamespaceRequestFieldNamespaceID     = big.NewInt(1 << 0)
	deleteNamespaceRequestFieldExpectedHeadSeq = big.NewInt(1 << 1)
)

type DeleteNamespaceRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Delete only if the namespace head is still at this sequence
	ExpectedHeadSeq *ChangeSeq `json:"-" url:"expected_head_seq,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteNamespaceRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteNamespaceRequest) SetNamespaceID(namespaceID string) {
	d.NamespaceID = namespaceID
	d.require(deleteNamespaceRequestFieldNamespaceID)
}

// SetExpectedHeadSeq sets the ExpectedHeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteNamespaceRequest) SetExpectedHeadSeq(expectedHeadSeq *ChangeSeq) {
	d.ExpectedHeadSeq = expectedHeadSeq
	d.require(deleteNamespaceRequestFieldExpectedHeadSeq)
}

var (
	forkNamespaceRequestFieldNamespaceID    = big.NewInt(1 << 0)
	forkNamespaceRequestFieldNewNamespaceID = big.NewInt(1 << 1)
	forkNamespaceRequestFieldSnapshotID     = big.NewInt(1 << 2)
)

type ForkNamespaceRequest struct {
	// Source namespace id
	NamespaceID string `json:"-" url:"-"`
	// Durable namespace id for the fork target.
	NewNamespaceID NamespaceID `json:"new_namespace_id" url:"-"`
	// Fork from this live snapshot instead of the current head.
	SnapshotID *PinID `json:"snapshot_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *ForkNamespaceRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForkNamespaceRequest) SetNamespaceID(namespaceID string) {
	f.NamespaceID = namespaceID
	f.require(forkNamespaceRequestFieldNamespaceID)
}

// SetNewNamespaceID sets the NewNamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForkNamespaceRequest) SetNewNamespaceID(newNamespaceID NamespaceID) {
	f.NewNamespaceID = newNamespaceID
	f.require(forkNamespaceRequestFieldNewNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForkNamespaceRequest) SetSnapshotID(snapshotID *PinID) {
	f.SnapshotID = snapshotID
	f.require(forkNamespaceRequestFieldSnapshotID)
}

func (f *ForkNamespaceRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ForkNamespaceRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*f = ForkNamespaceRequest(body)
	return nil
}

func (f *ForkNamespaceRequest) MarshalJSON() ([]byte, error) {
	type embed ForkNamespaceRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getNamespaceRequestFieldNamespaceID = big.NewInt(1 << 0)
)

type GetNamespaceRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetNamespaceRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNamespaceRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(getNamespaceRequestFieldNamespaceID)
}

// Result of deleting a namespace.
var (
	deleteNamespaceResponseFieldHeadSeq     = big.NewInt(1 << 0)
	deleteNamespaceResponseFieldNamespaceID = big.NewInt(1 << 1)
)

type DeleteNamespaceResponse struct {
	// The final committed sequence before the namespace was deleted.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Namespace whose history ended.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteNamespaceResponse) GetHeadSeq() ChangeSeq {
	if d == nil {
		return 0
	}
	return d.HeadSeq
}

func (d *DeleteNamespaceResponse) GetNamespaceID() NamespaceID {
	if d == nil {
		return ""
	}
	return d.NamespaceID
}

func (d *DeleteNamespaceResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteNamespaceResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteNamespaceResponse) SetHeadSeq(headSeq ChangeSeq) {
	d.HeadSeq = headSeq
	d.require(deleteNamespaceResponseFieldHeadSeq)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteNamespaceResponse) SetNamespaceID(namespaceID NamespaceID) {
	d.NamespaceID = namespaceID
	d.require(deleteNamespaceResponseFieldNamespaceID)
}

func (d *DeleteNamespaceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteNamespaceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteNamespaceResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteNamespaceResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteNamespaceResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteNamespaceResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Current state for one namespace.
var (
	namespaceFieldAccess            = big.NewInt(1 << 0)
	namespaceFieldCreatedAtMs       = big.NewInt(1 << 1)
	namespaceFieldCreatedBy         = big.NewInt(1 << 2)
	namespaceFieldForkBasis         = big.NewInt(1 << 3)
	namespaceFieldHeadSeq           = big.NewInt(1 << 4)
	namespaceFieldNamespaceID       = big.NewInt(1 << 5)
	namespaceFieldRetentionFloorSeq = big.NewInt(1 << 6)
)

type Namespace struct {
	// The namespace's access mode.
	Access *NamespaceAccessMode `json:"access" url:"access"`
	// Time the namespace was created, in Unix milliseconds.
	CreatedAtMs int64 `json:"created_at_ms" url:"created_at_ms"`
	// Actor that created the namespace, as supplied by the application.
	CreatedBy ActorID `json:"created_by" url:"created_by"`
	// Present only for a fork: the source it was forked from.
	ForkBasis *NamespaceForkBasis `json:"fork_basis,omitempty" url:"fork_basis,omitempty"`
	// Current visible namespace sequence.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Namespace ID.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Oldest sequence still promised for incremental replay.
	RetentionFloorSeq ChangeSeq `json:"retention_floor_seq" url:"retention_floor_seq"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *Namespace) GetAccess() *NamespaceAccessMode {
	if n == nil {
		return nil
	}
	return n.Access
}

func (n *Namespace) GetCreatedAtMs() int64 {
	if n == nil {
		return 0
	}
	return n.CreatedAtMs
}

func (n *Namespace) GetCreatedBy() ActorID {
	if n == nil {
		return ""
	}
	return n.CreatedBy
}

func (n *Namespace) GetForkBasis() *NamespaceForkBasis {
	if n == nil {
		return nil
	}
	return n.ForkBasis
}

func (n *Namespace) GetHeadSeq() ChangeSeq {
	if n == nil {
		return 0
	}
	return n.HeadSeq
}

func (n *Namespace) GetNamespaceID() NamespaceID {
	if n == nil {
		return ""
	}
	return n.NamespaceID
}

func (n *Namespace) GetRetentionFloorSeq() ChangeSeq {
	if n == nil {
		return 0
	}
	return n.RetentionFloorSeq
}

func (n *Namespace) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *Namespace) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetAccess sets the Access field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetAccess(access *NamespaceAccessMode) {
	n.Access = access
	n.require(namespaceFieldAccess)
}

// SetCreatedAtMs sets the CreatedAtMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetCreatedAtMs(createdAtMs int64) {
	n.CreatedAtMs = createdAtMs
	n.require(namespaceFieldCreatedAtMs)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetCreatedBy(createdBy ActorID) {
	n.CreatedBy = createdBy
	n.require(namespaceFieldCreatedBy)
}

// SetForkBasis sets the ForkBasis field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetForkBasis(forkBasis *NamespaceForkBasis) {
	n.ForkBasis = forkBasis
	n.require(namespaceFieldForkBasis)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetHeadSeq(headSeq ChangeSeq) {
	n.HeadSeq = headSeq
	n.require(namespaceFieldHeadSeq)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetNamespaceID(namespaceID NamespaceID) {
	n.NamespaceID = namespaceID
	n.require(namespaceFieldNamespaceID)
}

// SetRetentionFloorSeq sets the RetentionFloorSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetRetentionFloorSeq(retentionFloorSeq ChangeSeq) {
	n.RetentionFloorSeq = retentionFloorSeq
	n.require(namespaceFieldRetentionFloorSeq)
}

func (n *Namespace) UnmarshalJSON(data []byte) error {
	type unmarshaler Namespace
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = Namespace(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *Namespace) MarshalJSON() ([]byte, error) {
	type embed Namespace
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *Namespace) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// A namespace's access mode, fixed at creation.
type NamespaceAccess struct {
	Kind         string
	ACL          *NamespaceAccessACL
	Unrestricted *NamespaceAccessUnrestricted

	rawJSON json.RawMessage
}

func (n *NamespaceAccess) GetKind() string {
	if n == nil {
		return ""
	}
	return n.Kind
}

func (n *NamespaceAccess) GetACL() *NamespaceAccessACL {
	if n == nil {
		return nil
	}
	return n.ACL
}

func (n *NamespaceAccess) GetUnrestricted() *NamespaceAccessUnrestricted {
	if n == nil {
		return nil
	}
	return n.Unrestricted
}

func (n *NamespaceAccess) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	n.Kind = unmarshaler.Kind
	if unmarshaler.Kind == "" {
		return fmt.Errorf("%T did not include discriminant kind", n)
	}
	switch unmarshaler.Kind {
	case "acl":
		value := new(NamespaceAccessACL)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.ACL = value
	case "unrestricted":
		value := new(NamespaceAccessUnrestricted)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.Unrestricted = value
	}
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n NamespaceAccess) MarshalJSON() ([]byte, error) {
	if err := n.validate(); err != nil {
		return nil, err
	}
	if n.ACL != nil {
		return internal.MarshalJSONWithExtraProperty(n.ACL, "kind", "acl")
	}
	if n.Unrestricted != nil {
		return internal.MarshalJSONWithExtraProperty(n.Unrestricted, "kind", "unrestricted")
	}
	if len(n.rawJSON) > 0 {
		return n.rawJSON, nil
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", n)
}

type NamespaceAccessVisitor interface {
	VisitACL(*NamespaceAccessACL) error
	VisitUnrestricted(*NamespaceAccessUnrestricted) error
}

func (n *NamespaceAccess) Accept(visitor NamespaceAccessVisitor) error {
	if n.ACL != nil {
		return visitor.VisitACL(n.ACL)
	}
	if n.Unrestricted != nil {
		return visitor.VisitUnrestricted(n.Unrestricted)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", n)
}

func (n *NamespaceAccess) validate() error {
	if n == nil {
		return fmt.Errorf("type %T is nil", n)
	}
	var fields []string
	if n.ACL != nil {
		fields = append(fields, "acl")
	}
	if n.Unrestricted != nil {
		fields = append(fields, "unrestricted")
	}
	if len(fields) == 0 {
		if n.Kind != "" {
			if len(n.rawJSON) > 0 {
				return nil
			}
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", n, n.Kind)
		}
		return fmt.Errorf("type %T is empty", n)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", n, fields)
	}
	if n.Kind != "" {
		field := fields[0]
		if n.Kind != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				n,
				n.Kind,
				n,
			)
		}
	}
	return nil
}

// Access rows govern every operation.
var (
	namespaceAccessACLFieldPrincipalScope = big.NewInt(1 << 0)
	namespaceAccessACLFieldRootGrants     = big.NewInt(1 << 1)
)

type NamespaceAccessACL struct {
	// Identity domain the namespace's principal ids belong to.
	PrincipalScope PrincipalScope `json:"principal_scope" url:"principal_scope"`
	// The root inode's grants at genesis, normally `admin` for each
	// initial administrator.
	RootGrants AccessGrants `json:"root_grants" url:"root_grants"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NamespaceAccessACL) GetPrincipalScope() PrincipalScope {
	if n == nil {
		return ""
	}
	return n.PrincipalScope
}

func (n *NamespaceAccessACL) GetRootGrants() AccessGrants {
	if n == nil {
		return nil
	}
	return n.RootGrants
}

func (n *NamespaceAccessACL) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NamespaceAccessACL) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetPrincipalScope sets the PrincipalScope field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NamespaceAccessACL) SetPrincipalScope(principalScope PrincipalScope) {
	n.PrincipalScope = principalScope
	n.require(namespaceAccessACLFieldPrincipalScope)
}

// SetRootGrants sets the RootGrants field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NamespaceAccessACL) SetRootGrants(rootGrants AccessGrants) {
	n.RootGrants = rootGrants
	n.require(namespaceAccessACLFieldRootGrants)
}

func (n *NamespaceAccessACL) UnmarshalJSON(data []byte) error {
	type unmarshaler NamespaceAccessACL
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NamespaceAccessACL(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NamespaceAccessACL) MarshalJSON() ([]byte, error) {
	type embed NamespaceAccessACL
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NamespaceAccessACL) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// A namespace's access mode as reported, without its genesis grants.
type NamespaceAccessMode struct {
	Kind         string
	ACL          *NamespaceAccessModeACL
	Unrestricted *NamespaceAccessModeUnrestricted

	rawJSON json.RawMessage
}

func (n *NamespaceAccessMode) GetKind() string {
	if n == nil {
		return ""
	}
	return n.Kind
}

func (n *NamespaceAccessMode) GetACL() *NamespaceAccessModeACL {
	if n == nil {
		return nil
	}
	return n.ACL
}

func (n *NamespaceAccessMode) GetUnrestricted() *NamespaceAccessModeUnrestricted {
	if n == nil {
		return nil
	}
	return n.Unrestricted
}

func (n *NamespaceAccessMode) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	n.Kind = unmarshaler.Kind
	if unmarshaler.Kind == "" {
		return fmt.Errorf("%T did not include discriminant kind", n)
	}
	switch unmarshaler.Kind {
	case "acl":
		value := new(NamespaceAccessModeACL)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.ACL = value
	case "unrestricted":
		value := new(NamespaceAccessModeUnrestricted)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.Unrestricted = value
	}
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n NamespaceAccessMode) MarshalJSON() ([]byte, error) {
	if err := n.validate(); err != nil {
		return nil, err
	}
	if n.ACL != nil {
		return internal.MarshalJSONWithExtraProperty(n.ACL, "kind", "acl")
	}
	if n.Unrestricted != nil {
		return internal.MarshalJSONWithExtraProperty(n.Unrestricted, "kind", "unrestricted")
	}
	if len(n.rawJSON) > 0 {
		return n.rawJSON, nil
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", n)
}

type NamespaceAccessModeVisitor interface {
	VisitACL(*NamespaceAccessModeACL) error
	VisitUnrestricted(*NamespaceAccessModeUnrestricted) error
}

func (n *NamespaceAccessMode) Accept(visitor NamespaceAccessModeVisitor) error {
	if n.ACL != nil {
		return visitor.VisitACL(n.ACL)
	}
	if n.Unrestricted != nil {
		return visitor.VisitUnrestricted(n.Unrestricted)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", n)
}

func (n *NamespaceAccessMode) validate() error {
	if n == nil {
		return fmt.Errorf("type %T is nil", n)
	}
	var fields []string
	if n.ACL != nil {
		fields = append(fields, "acl")
	}
	if n.Unrestricted != nil {
		fields = append(fields, "unrestricted")
	}
	if len(fields) == 0 {
		if n.Kind != "" {
			if len(n.rawJSON) > 0 {
				return nil
			}
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", n, n.Kind)
		}
		return fmt.Errorf("type %T is empty", n)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", n, fields)
	}
	if n.Kind != "" {
		field := fields[0]
		if n.Kind != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				n,
				n.Kind,
				n,
			)
		}
	}
	return nil
}

// Access rows govern operations in this identity domain.
var (
	namespaceAccessModeACLFieldPrincipalScope = big.NewInt(1 << 0)
)

type NamespaceAccessModeACL struct {
	// Identity domain the namespace's principal ids belong to.
	PrincipalScope PrincipalScope `json:"principal_scope" url:"principal_scope"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NamespaceAccessModeACL) GetPrincipalScope() PrincipalScope {
	if n == nil {
		return ""
	}
	return n.PrincipalScope
}

func (n *NamespaceAccessModeACL) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NamespaceAccessModeACL) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetPrincipalScope sets the PrincipalScope field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NamespaceAccessModeACL) SetPrincipalScope(principalScope PrincipalScope) {
	n.PrincipalScope = principalScope
	n.require(namespaceAccessModeACLFieldPrincipalScope)
}

func (n *NamespaceAccessModeACL) UnmarshalJSON(data []byte) error {
	type unmarshaler NamespaceAccessModeACL
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NamespaceAccessModeACL(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NamespaceAccessModeACL) MarshalJSON() ([]byte, error) {
	type embed NamespaceAccessModeACL
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NamespaceAccessModeACL) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Every caller holding the deployment credential may do everything.
type NamespaceAccessModeUnrestricted struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NamespaceAccessModeUnrestricted) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NamespaceAccessModeUnrestricted) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

func (n *NamespaceAccessModeUnrestricted) UnmarshalJSON(data []byte) error {
	type unmarshaler NamespaceAccessModeUnrestricted
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NamespaceAccessModeUnrestricted(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NamespaceAccessModeUnrestricted) MarshalJSON() ([]byte, error) {
	type embed NamespaceAccessModeUnrestricted
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NamespaceAccessModeUnrestricted) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Every caller holding the deployment credential may do everything.
type NamespaceAccessUnrestricted struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NamespaceAccessUnrestricted) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NamespaceAccessUnrestricted) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

func (n *NamespaceAccessUnrestricted) UnmarshalJSON(data []byte) error {
	type unmarshaler NamespaceAccessUnrestricted
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NamespaceAccessUnrestricted(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NamespaceAccessUnrestricted) MarshalJSON() ([]byte, error) {
	type embed NamespaceAccessUnrestricted
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NamespaceAccessUnrestricted) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Opaque identity-domain id containing 1 to 256 visible ASCII characters other than the comma.
type PrincipalScope = string
