// Code generated by Fern. DO NOT EDIT.

package loonfs

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	createNamespaceRequestFieldNamespaceID = big.NewInt(1 << 0)
)

type CreateNamespaceRequest struct {
	// Durable namespace id to create.
	NamespaceID NamespaceID `json:"namespace_id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateNamespaceRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNamespaceRequest) SetNamespaceID(namespaceID NamespaceID) {
	c.NamespaceID = namespaceID
	c.require(createNamespaceRequestFieldNamespaceID)
}

func (c *CreateNamespaceRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateNamespaceRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateNamespaceRequest(body)
	return nil
}

func (c *CreateNamespaceRequest) MarshalJSON() ([]byte, error) {
	type embed CreateNamespaceRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createSnapshotRequestFieldNamespaceID = big.NewInt(1 << 0)
	createSnapshotRequestFieldName        = big.NewInt(1 << 1)
	createSnapshotRequestFieldTTLMs       = big.NewInt(1 << 2)
)

type CreateSnapshotRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// A label that does not need to be unique.
	Name string `json:"name" url:"-"`
	// Snapshot lifetime from the current server time, in milliseconds.
	TTLMs int64 `json:"ttl_ms" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSnapshotRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSnapshotRequest) SetNamespaceID(namespaceID string) {
	c.NamespaceID = namespaceID
	c.require(createSnapshotRequestFieldNamespaceID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSnapshotRequest) SetName(name string) {
	c.Name = name
	c.require(createSnapshotRequestFieldName)
}

// SetTTLMs sets the TTLMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSnapshotRequest) SetTTLMs(ttlMs int64) {
	c.TTLMs = ttlMs
	c.require(createSnapshotRequestFieldTTLMs)
}

func (c *CreateSnapshotRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSnapshotRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateSnapshotRequest(body)
	return nil
}

func (c *CreateSnapshotRequest) MarshalJSON() ([]byte, error) {
	type embed CreateSnapshotRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteNamespaceRequestFieldNamespaceID     = big.NewInt(1 << 0)
	deleteNamespaceRequestFieldExpectedHeadSeq = big.NewInt(1 << 1)
)

type DeleteNamespaceRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Delete only if the namespace head is still at this sequence
	ExpectedHeadSeq *ChangeSeq `json:"-" url:"expected_head_seq,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteNamespaceRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteNamespaceRequest) SetNamespaceID(namespaceID string) {
	d.NamespaceID = namespaceID
	d.require(deleteNamespaceRequestFieldNamespaceID)
}

// SetExpectedHeadSeq sets the ExpectedHeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteNamespaceRequest) SetExpectedHeadSeq(expectedHeadSeq *ChangeSeq) {
	d.ExpectedHeadSeq = expectedHeadSeq
	d.require(deleteNamespaceRequestFieldExpectedHeadSeq)
}

var (
	extendSnapshotRequestFieldNamespaceID = big.NewInt(1 << 0)
	extendSnapshotRequestFieldSnapshotID  = big.NewInt(1 << 1)
	extendSnapshotRequestFieldTTLMs       = big.NewInt(1 << 2)
)

type ExtendSnapshotRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Snapshot id
	SnapshotID string `json:"-" url:"-"`
	// Requested lifetime from the server's current time, in milliseconds.
	TTLMs int64 `json:"ttl_ms" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (e *ExtendSnapshotRequest) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExtendSnapshotRequest) SetNamespaceID(namespaceID string) {
	e.NamespaceID = namespaceID
	e.require(extendSnapshotRequestFieldNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExtendSnapshotRequest) SetSnapshotID(snapshotID string) {
	e.SnapshotID = snapshotID
	e.require(extendSnapshotRequestFieldSnapshotID)
}

// SetTTLMs sets the TTLMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExtendSnapshotRequest) SetTTLMs(ttlMs int64) {
	e.TTLMs = ttlMs
	e.require(extendSnapshotRequestFieldTTLMs)
}

func (e *ExtendSnapshotRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ExtendSnapshotRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*e = ExtendSnapshotRequest(body)
	return nil
}

func (e *ExtendSnapshotRequest) MarshalJSON() ([]byte, error) {
	type embed ExtendSnapshotRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	forkNamespaceRequestFieldNamespaceID    = big.NewInt(1 << 0)
	forkNamespaceRequestFieldNewNamespaceID = big.NewInt(1 << 1)
)

type ForkNamespaceRequest struct {
	// Source namespace id
	NamespaceID string `json:"-" url:"-"`
	// Durable namespace id for the fork target.
	NewNamespaceID NamespaceID `json:"new_namespace_id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *ForkNamespaceRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForkNamespaceRequest) SetNamespaceID(namespaceID string) {
	f.NamespaceID = namespaceID
	f.require(forkNamespaceRequestFieldNamespaceID)
}

// SetNewNamespaceID sets the NewNamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForkNamespaceRequest) SetNewNamespaceID(newNamespaceID NamespaceID) {
	f.NewNamespaceID = newNamespaceID
	f.require(forkNamespaceRequestFieldNewNamespaceID)
}

func (f *ForkNamespaceRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ForkNamespaceRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*f = ForkNamespaceRequest(body)
	return nil
}

func (f *ForkNamespaceRequest) MarshalJSON() ([]byte, error) {
	type embed ForkNamespaceRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getNamespaceRequestFieldNamespaceID = big.NewInt(1 << 0)
)

type GetNamespaceRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetNamespaceRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNamespaceRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(getNamespaceRequestFieldNamespaceID)
}

var (
	listSnapshotsRequestFieldNamespaceID = big.NewInt(1 << 0)
	listSnapshotsRequestFieldLimit       = big.NewInt(1 << 1)
	listSnapshotsRequestFieldCursor      = big.NewInt(1 << 2)
)

type ListSnapshotsRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Maximum page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque snapshot-list page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSnapshotsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsRequest) SetNamespaceID(namespaceID string) {
	l.NamespaceID = namespaceID
	l.require(listSnapshotsRequestFieldNamespaceID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listSnapshotsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listSnapshotsRequestFieldCursor)
}

var (
	releaseSnapshotRequestFieldNamespaceID = big.NewInt(1 << 0)
	releaseSnapshotRequestFieldSnapshotID  = big.NewInt(1 << 1)
)

type ReleaseSnapshotRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Snapshot id
	SnapshotID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReleaseSnapshotRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseSnapshotRequest) SetNamespaceID(namespaceID string) {
	r.NamespaceID = namespaceID
	r.require(releaseSnapshotRequestFieldNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseSnapshotRequest) SetSnapshotID(snapshotID string) {
	r.SnapshotID = snapshotID
	r.require(releaseSnapshotRequestFieldSnapshotID)
}

// Result of deleting a namespace.
var (
	deleteNamespaceResponseFieldHeadSeq     = big.NewInt(1 << 0)
	deleteNamespaceResponseFieldNamespaceID = big.NewInt(1 << 1)
)

type DeleteNamespaceResponse struct {
	// The head's last committed sequence; the delete linearized
	// immediately after it, so this is where history ended.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Namespace whose history ended.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteNamespaceResponse) GetHeadSeq() ChangeSeq {
	if d == nil {
		return 0
	}
	return d.HeadSeq
}

func (d *DeleteNamespaceResponse) GetNamespaceID() NamespaceID {
	if d == nil {
		return ""
	}
	return d.NamespaceID
}

func (d *DeleteNamespaceResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteNamespaceResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteNamespaceResponse) SetHeadSeq(headSeq ChangeSeq) {
	d.HeadSeq = headSeq
	d.require(deleteNamespaceResponseFieldHeadSeq)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteNamespaceResponse) SetNamespaceID(namespaceID NamespaceID) {
	d.NamespaceID = namespaceID
	d.require(deleteNamespaceResponseFieldNamespaceID)
}

func (d *DeleteNamespaceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteNamespaceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteNamespaceResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteNamespaceResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteNamespaceResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteNamespaceResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// One page of live read snapshots.
var (
	listSnapshotsResponseFieldNamespaceID = big.NewInt(1 << 0)
	listSnapshotsResponseFieldNextCursor  = big.NewInt(1 << 1)
	listSnapshotsResponseFieldSnapshots   = big.NewInt(1 << 2)
)

type ListSnapshotsResponse struct {
	// Namespace the snapshots belong to.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Opaque cursor for the next page.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// Live snapshot records in ascending snapshot-id order.
	Snapshots []*SnapshotSummary `json:"snapshots" url:"snapshots"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSnapshotsResponse) GetNamespaceID() NamespaceID {
	if l == nil {
		return ""
	}
	return l.NamespaceID
}

func (l *ListSnapshotsResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListSnapshotsResponse) GetSnapshots() []*SnapshotSummary {
	if l == nil {
		return nil
	}
	return l.Snapshots
}

func (l *ListSnapshotsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSnapshotsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsResponse) SetNamespaceID(namespaceID NamespaceID) {
	l.NamespaceID = namespaceID
	l.require(listSnapshotsResponseFieldNamespaceID)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsResponse) SetNextCursor(nextCursor *string) {
	l.NextCursor = nextCursor
	l.require(listSnapshotsResponseFieldNextCursor)
}

// SetSnapshots sets the Snapshots field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsResponse) SetSnapshots(snapshots []*SnapshotSummary) {
	l.Snapshots = snapshots
	l.require(listSnapshotsResponseFieldSnapshots)
}

func (l *ListSnapshotsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSnapshotsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSnapshotsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSnapshotsResponse) MarshalJSON() ([]byte, error) {
	type embed ListSnapshotsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSnapshotsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Current state for one namespace.
var (
	namespaceFieldHeadSeq           = big.NewInt(1 << 0)
	namespaceFieldNamespaceID       = big.NewInt(1 << 1)
	namespaceFieldRetentionFloorSeq = big.NewInt(1 << 2)
)

type Namespace struct {
	// Current visible namespace sequence.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Namespace ID.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Oldest sequence still promised for incremental replay.
	RetentionFloorSeq ChangeSeq `json:"retention_floor_seq" url:"retention_floor_seq"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *Namespace) GetHeadSeq() ChangeSeq {
	if n == nil {
		return 0
	}
	return n.HeadSeq
}

func (n *Namespace) GetNamespaceID() NamespaceID {
	if n == nil {
		return ""
	}
	return n.NamespaceID
}

func (n *Namespace) GetRetentionFloorSeq() ChangeSeq {
	if n == nil {
		return 0
	}
	return n.RetentionFloorSeq
}

func (n *Namespace) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *Namespace) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetHeadSeq(headSeq ChangeSeq) {
	n.HeadSeq = headSeq
	n.require(namespaceFieldHeadSeq)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetNamespaceID(namespaceID NamespaceID) {
	n.NamespaceID = namespaceID
	n.require(namespaceFieldNamespaceID)
}

// SetRetentionFloorSeq sets the RetentionFloorSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Namespace) SetRetentionFloorSeq(retentionFloorSeq ChangeSeq) {
	n.RetentionFloorSeq = retentionFloorSeq
	n.require(namespaceFieldRetentionFloorSeq)
}

func (n *Namespace) UnmarshalJSON(data []byte) error {
	type unmarshaler Namespace
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = Namespace(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *Namespace) MarshalJSON() ([]byte, error) {
	type embed Namespace
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *Namespace) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Result of releasing a read snapshot.
var (
	releaseSnapshotResponseFieldNamespaceID = big.NewInt(1 << 0)
	releaseSnapshotResponseFieldSnapshotID  = big.NewInt(1 << 1)
)

type ReleaseSnapshotResponse struct {
	// Namespace the snapshot belonged to.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Released snapshot id.
	SnapshotID CheckpointID `json:"snapshot_id" url:"snapshot_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReleaseSnapshotResponse) GetNamespaceID() NamespaceID {
	if r == nil {
		return ""
	}
	return r.NamespaceID
}

func (r *ReleaseSnapshotResponse) GetSnapshotID() CheckpointID {
	if r == nil {
		return ""
	}
	return r.SnapshotID
}

func (r *ReleaseSnapshotResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReleaseSnapshotResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseSnapshotResponse) SetNamespaceID(namespaceID NamespaceID) {
	r.NamespaceID = namespaceID
	r.require(releaseSnapshotResponseFieldNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReleaseSnapshotResponse) SetSnapshotID(snapshotID CheckpointID) {
	r.SnapshotID = snapshotID
	r.require(releaseSnapshotResponseFieldSnapshotID)
}

func (r *ReleaseSnapshotResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReleaseSnapshotResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReleaseSnapshotResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReleaseSnapshotResponse) MarshalJSON() ([]byte, error) {
	type embed ReleaseSnapshotResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReleaseSnapshotResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// A live snapshot.
var (
	snapshotSummaryFieldCreatedAtMs = big.NewInt(1 << 0)
	snapshotSummaryFieldExpiresAtMs = big.NewInt(1 << 1)
	snapshotSummaryFieldHeadSeq     = big.NewInt(1 << 2)
	snapshotSummaryFieldName        = big.NewInt(1 << 3)
	snapshotSummaryFieldNamespaceID = big.NewInt(1 << 4)
	snapshotSummaryFieldSnapshotID  = big.NewInt(1 << 5)
)

type SnapshotSummary struct {
	// Time the snapshot record was created, in Unix milliseconds.
	CreatedAtMs int64 `json:"created_at_ms" url:"created_at_ms"`
	// When the snapshot lease expires, in Unix milliseconds.
	ExpiresAtMs int64 `json:"expires_at_ms" url:"expires_at_ms"`
	// Namespace sequence captured by the snapshot.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Snapshot label.
	Name string `json:"name" url:"name"`
	// Namespace whose state the snapshot captured.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Snapshot id.
	SnapshotID CheckpointID `json:"snapshot_id" url:"snapshot_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SnapshotSummary) GetCreatedAtMs() int64 {
	if s == nil {
		return 0
	}
	return s.CreatedAtMs
}

func (s *SnapshotSummary) GetExpiresAtMs() int64 {
	if s == nil {
		return 0
	}
	return s.ExpiresAtMs
}

func (s *SnapshotSummary) GetHeadSeq() ChangeSeq {
	if s == nil {
		return 0
	}
	return s.HeadSeq
}

func (s *SnapshotSummary) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SnapshotSummary) GetNamespaceID() NamespaceID {
	if s == nil {
		return ""
	}
	return s.NamespaceID
}

func (s *SnapshotSummary) GetSnapshotID() CheckpointID {
	if s == nil {
		return ""
	}
	return s.SnapshotID
}

func (s *SnapshotSummary) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SnapshotSummary) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCreatedAtMs sets the CreatedAtMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotSummary) SetCreatedAtMs(createdAtMs int64) {
	s.CreatedAtMs = createdAtMs
	s.require(snapshotSummaryFieldCreatedAtMs)
}

// SetExpiresAtMs sets the ExpiresAtMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotSummary) SetExpiresAtMs(expiresAtMs int64) {
	s.ExpiresAtMs = expiresAtMs
	s.require(snapshotSummaryFieldExpiresAtMs)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotSummary) SetHeadSeq(headSeq ChangeSeq) {
	s.HeadSeq = headSeq
	s.require(snapshotSummaryFieldHeadSeq)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotSummary) SetName(name string) {
	s.Name = name
	s.require(snapshotSummaryFieldName)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotSummary) SetNamespaceID(namespaceID NamespaceID) {
	s.NamespaceID = namespaceID
	s.require(snapshotSummaryFieldNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotSummary) SetSnapshotID(snapshotID CheckpointID) {
	s.SnapshotID = snapshotID
	s.require(snapshotSummaryFieldSnapshotID)
}

func (s *SnapshotSummary) UnmarshalJSON(data []byte) error {
	type unmarshaler SnapshotSummary
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SnapshotSummary(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SnapshotSummary) MarshalJSON() ([]byte, error) {
	type embed SnapshotSummary
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SnapshotSummary) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
