// Code generated by Fern. DO NOT EDIT.

package loonfs

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	grepRequestFieldNamespaceID     = big.NewInt(1 << 0)
	grepRequestFieldPattern         = big.NewInt(1 << 1)
	grepRequestFieldCaseInsensitive = big.NewInt(1 << 2)
	grepRequestFieldPathPrefix      = big.NewInt(1 << 3)
	grepRequestFieldAllowScan       = big.NewInt(1 << 4)
	grepRequestFieldAllowStale      = big.NewInt(1 << 5)
	grepRequestFieldLimit           = big.NewInt(1 << 6)
	grepRequestFieldCursor          = big.NewInt(1 << 7)
)

type GrepRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Pattern in the Rust `regex` crate's dialect. Its UTF-8 encoding must be at most 1024 bytes.
	Pattern string `json:"-" url:"pattern"`
	// Match case-insensitively (`true` or `false`). Defaults to `false`.
	CaseInsensitive *bool `json:"-" url:"case_insensitive,omitempty"`
	// Complete absolute path used to restrict matches.
	PathPrefix *string `json:"-" url:"path_prefix,omitempty"`
	// Permit a capped exhaustive scan when the pattern has no required grams (`true` or `false`). Defaults to `false`.
	AllowScan *bool `json:"-" url:"allow_scan,omitempty"`
	// Return indexed-only results when the unindexed tail exceeds the scan budget (`true` or `false`). Defaults to `false`.
	AllowStale *bool `json:"-" url:"allow_stale,omitempty"`
	// Maximum matches per page
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque grep page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GrepRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(grepRequestFieldNamespaceID)
}

// SetPattern sets the Pattern field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetPattern(pattern string) {
	g.Pattern = pattern
	g.require(grepRequestFieldPattern)
}

// SetCaseInsensitive sets the CaseInsensitive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetCaseInsensitive(caseInsensitive *bool) {
	g.CaseInsensitive = caseInsensitive
	g.require(grepRequestFieldCaseInsensitive)
}

// SetPathPrefix sets the PathPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetPathPrefix(pathPrefix *string) {
	g.PathPrefix = pathPrefix
	g.require(grepRequestFieldPathPrefix)
}

// SetAllowScan sets the AllowScan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetAllowScan(allowScan *bool) {
	g.AllowScan = allowScan
	g.require(grepRequestFieldAllowScan)
}

// SetAllowStale sets the AllowStale field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetAllowStale(allowStale *bool) {
	g.AllowStale = allowStale
	g.require(grepRequestFieldAllowStale)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(grepRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepRequest) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(grepRequestFieldCursor)
}

// One line-oriented match.
var (
	grepMatchFieldByteOffset    = big.NewInt(1 << 0)
	grepMatchFieldInodeID       = big.NewInt(1 << 1)
	grepMatchFieldLine          = big.NewInt(1 << 2)
	grepMatchFieldLineNumber    = big.NewInt(1 << 3)
	grepMatchFieldLineTruncated = big.NewInt(1 << 4)
	grepMatchFieldPath          = big.NewInt(1 << 5)
	grepMatchFieldRevisionNo    = big.NewInt(1 << 6)
)

type GrepMatch struct {
	// Byte offset of the match within the file.
	ByteOffset int64 `json:"byte_offset" url:"byte_offset"`
	// Stable inode ID within a namespace
	InodeID string `json:"inode_id" url:"inode_id"`
	// The matching line, truncated to the server's line cap.
	Line string `json:"line" url:"line"`
	// One-based line number of the match.
	LineNumber int64 `json:"line_number" url:"line_number"`
	// True when `line` was truncated.
	LineTruncated *bool `json:"line_truncated,omitempty" url:"line_truncated,omitempty"`
	// The file's absolute path, derived at the snapshot.
	Path AbsolutePath `json:"path" url:"path"`
	// The matched revision (the newest visible one at the snapshot).
	RevisionNo RevisionNo `json:"revision_no" url:"revision_no"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GrepMatch) GetByteOffset() int64 {
	if g == nil {
		return 0
	}
	return g.ByteOffset
}

func (g *GrepMatch) GetInodeID() string {
	if g == nil {
		return ""
	}
	return g.InodeID
}

func (g *GrepMatch) GetLine() string {
	if g == nil {
		return ""
	}
	return g.Line
}

func (g *GrepMatch) GetLineNumber() int64 {
	if g == nil {
		return 0
	}
	return g.LineNumber
}

func (g *GrepMatch) GetLineTruncated() *bool {
	if g == nil {
		return nil
	}
	return g.LineTruncated
}

func (g *GrepMatch) GetPath() AbsolutePath {
	if g == nil {
		return ""
	}
	return g.Path
}

func (g *GrepMatch) GetRevisionNo() RevisionNo {
	if g == nil {
		return 0
	}
	return g.RevisionNo
}

func (g *GrepMatch) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GrepMatch) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetByteOffset sets the ByteOffset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetByteOffset(byteOffset int64) {
	g.ByteOffset = byteOffset
	g.require(grepMatchFieldByteOffset)
}

// SetInodeID sets the InodeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetInodeID(inodeID string) {
	g.InodeID = inodeID
	g.require(grepMatchFieldInodeID)
}

// SetLine sets the Line field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetLine(line string) {
	g.Line = line
	g.require(grepMatchFieldLine)
}

// SetLineNumber sets the LineNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetLineNumber(lineNumber int64) {
	g.LineNumber = lineNumber
	g.require(grepMatchFieldLineNumber)
}

// SetLineTruncated sets the LineTruncated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetLineTruncated(lineTruncated *bool) {
	g.LineTruncated = lineTruncated
	g.require(grepMatchFieldLineTruncated)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetPath(path AbsolutePath) {
	g.Path = path
	g.require(grepMatchFieldPath)
}

// SetRevisionNo sets the RevisionNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepMatch) SetRevisionNo(revisionNo RevisionNo) {
	g.RevisionNo = revisionNo
	g.require(grepMatchFieldRevisionNo)
}

func (g *GrepMatch) UnmarshalJSON(data []byte) error {
	type unmarshaler GrepMatch
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GrepMatch(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GrepMatch) MarshalJSON() ([]byte, error) {
	type embed GrepMatch
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GrepMatch) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// One content-search page.
var (
	grepResponseFieldBuiltThroughSeq = big.NewInt(1 << 0)
	grepResponseFieldHeadSeq         = big.NewInt(1 << 1)
	grepResponseFieldMatches         = big.NewInt(1 << 2)
	grepResponseFieldNamespaceID     = big.NewInt(1 << 3)
	grepResponseFieldNextCursor      = big.NewInt(1 << 4)
	grepResponseFieldTailScanned     = big.NewInt(1 << 5)
)

type GrepResponse struct {
	// Commits at or below this sequence were answered from the index.
	BuiltThroughSeq ChangeSeq `json:"built_through_seq" url:"built_through_seq"`
	// Sequence this page was evaluated at. Pages are evaluated against
	// the namespace head at page time; the cursor is an ordering resume,
	// not a snapshot pin.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Matches in ascending `(inode_id, byte_offset)` order. A page may
	// return fewer matches than its limit and still carry a cursor: the
	// per-page verified-candidate budget bounds how much content one
	// request reads, whatever the plan's false-positive rate.
	Matches []*GrepMatch `json:"matches" url:"matches"`
	// Namespace searched.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Present when another page follows.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// True when revisions after `built_through_seq` were scanned
	// exhaustively; false only when `allow_stale` skipped them.
	TailScanned bool `json:"tail_scanned" url:"tail_scanned"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GrepResponse) GetBuiltThroughSeq() ChangeSeq {
	if g == nil {
		return 0
	}
	return g.BuiltThroughSeq
}

func (g *GrepResponse) GetHeadSeq() ChangeSeq {
	if g == nil {
		return 0
	}
	return g.HeadSeq
}

func (g *GrepResponse) GetMatches() []*GrepMatch {
	if g == nil {
		return nil
	}
	return g.Matches
}

func (g *GrepResponse) GetNamespaceID() NamespaceID {
	if g == nil {
		return ""
	}
	return g.NamespaceID
}

func (g *GrepResponse) GetNextCursor() *string {
	if g == nil {
		return nil
	}
	return g.NextCursor
}

func (g *GrepResponse) GetTailScanned() bool {
	if g == nil {
		return false
	}
	return g.TailScanned
}

func (g *GrepResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GrepResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBuiltThroughSeq sets the BuiltThroughSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetBuiltThroughSeq(builtThroughSeq ChangeSeq) {
	g.BuiltThroughSeq = builtThroughSeq
	g.require(grepResponseFieldBuiltThroughSeq)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetHeadSeq(headSeq ChangeSeq) {
	g.HeadSeq = headSeq
	g.require(grepResponseFieldHeadSeq)
}

// SetMatches sets the Matches field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetMatches(matches []*GrepMatch) {
	g.Matches = matches
	g.require(grepResponseFieldMatches)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetNamespaceID(namespaceID NamespaceID) {
	g.NamespaceID = namespaceID
	g.require(grepResponseFieldNamespaceID)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetNextCursor(nextCursor *string) {
	g.NextCursor = nextCursor
	g.require(grepResponseFieldNextCursor)
}

// SetTailScanned sets the TailScanned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrepResponse) SetTailScanned(tailScanned bool) {
	g.TailScanned = tailScanned
	g.require(grepResponseFieldTailScanned)
}

func (g *GrepResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GrepResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GrepResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GrepResponse) MarshalJSON() ([]byte, error) {
	type embed GrepResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GrepResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
