// Code generated by Fern. DO NOT EDIT.

package loonfs

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	createSnapshotRequestFieldNamespaceID = big.NewInt(1 << 0)
	createSnapshotRequestFieldName        = big.NewInt(1 << 1)
	createSnapshotRequestFieldTTLMs       = big.NewInt(1 << 2)
)

type CreateSnapshotRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// A label that does not need to be unique.
	Name string `json:"name" url:"-"`
	// Snapshot lifetime from the current server time, in milliseconds.
	TTLMs int64 `json:"ttl_ms" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSnapshotRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSnapshotRequest) SetNamespaceID(namespaceID string) {
	c.NamespaceID = namespaceID
	c.require(createSnapshotRequestFieldNamespaceID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSnapshotRequest) SetName(name string) {
	c.Name = name
	c.require(createSnapshotRequestFieldName)
}

// SetTTLMs sets the TTLMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSnapshotRequest) SetTTLMs(ttlMs int64) {
	c.TTLMs = ttlMs
	c.require(createSnapshotRequestFieldTTLMs)
}

func (c *CreateSnapshotRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSnapshotRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateSnapshotRequest(body)
	return nil
}

func (c *CreateSnapshotRequest) MarshalJSON() ([]byte, error) {
	type embed CreateSnapshotRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteSnapshotRequestFieldNamespaceID = big.NewInt(1 << 0)
	deleteSnapshotRequestFieldSnapshotID  = big.NewInt(1 << 1)
)

type DeleteSnapshotRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Snapshot id
	SnapshotID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteSnapshotRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSnapshotRequest) SetNamespaceID(namespaceID string) {
	d.NamespaceID = namespaceID
	d.require(deleteSnapshotRequestFieldNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSnapshotRequest) SetSnapshotID(snapshotID string) {
	d.SnapshotID = snapshotID
	d.require(deleteSnapshotRequestFieldSnapshotID)
}

var (
	extendSnapshotRequestFieldNamespaceID = big.NewInt(1 << 0)
	extendSnapshotRequestFieldSnapshotID  = big.NewInt(1 << 1)
	extendSnapshotRequestFieldTTLMs       = big.NewInt(1 << 2)
)

type ExtendSnapshotRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Snapshot id
	SnapshotID string `json:"-" url:"-"`
	// Requested lifetime from the server's current time, in milliseconds.
	TTLMs int64 `json:"ttl_ms" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (e *ExtendSnapshotRequest) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExtendSnapshotRequest) SetNamespaceID(namespaceID string) {
	e.NamespaceID = namespaceID
	e.require(extendSnapshotRequestFieldNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExtendSnapshotRequest) SetSnapshotID(snapshotID string) {
	e.SnapshotID = snapshotID
	e.require(extendSnapshotRequestFieldSnapshotID)
}

// SetTTLMs sets the TTLMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExtendSnapshotRequest) SetTTLMs(ttlMs int64) {
	e.TTLMs = ttlMs
	e.require(extendSnapshotRequestFieldTTLMs)
}

func (e *ExtendSnapshotRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ExtendSnapshotRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*e = ExtendSnapshotRequest(body)
	return nil
}

func (e *ExtendSnapshotRequest) MarshalJSON() ([]byte, error) {
	type embed ExtendSnapshotRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listSnapshotsRequestFieldNamespaceID = big.NewInt(1 << 0)
	listSnapshotsRequestFieldLimit       = big.NewInt(1 << 1)
	listSnapshotsRequestFieldCursor      = big.NewInt(1 << 2)
)

type ListSnapshotsRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Maximum page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque snapshot-list page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSnapshotsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsRequest) SetNamespaceID(namespaceID string) {
	l.NamespaceID = namespaceID
	l.require(listSnapshotsRequestFieldNamespaceID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listSnapshotsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listSnapshotsRequestFieldCursor)
}

// Identifies the snapshot record that was deleted.
var (
	deleteSnapshotResponseFieldNamespaceID = big.NewInt(1 << 0)
	deleteSnapshotResponseFieldSnapshotID  = big.NewInt(1 << 1)
)

type DeleteSnapshotResponse struct {
	// Namespace the snapshot belonged to.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Deleted snapshot record.
	SnapshotID CheckpointID `json:"snapshot_id" url:"snapshot_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteSnapshotResponse) GetNamespaceID() NamespaceID {
	if d == nil {
		return ""
	}
	return d.NamespaceID
}

func (d *DeleteSnapshotResponse) GetSnapshotID() CheckpointID {
	if d == nil {
		return ""
	}
	return d.SnapshotID
}

func (d *DeleteSnapshotResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteSnapshotResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSnapshotResponse) SetNamespaceID(namespaceID NamespaceID) {
	d.NamespaceID = namespaceID
	d.require(deleteSnapshotResponseFieldNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSnapshotResponse) SetSnapshotID(snapshotID CheckpointID) {
	d.SnapshotID = snapshotID
	d.require(deleteSnapshotResponseFieldSnapshotID)
}

func (d *DeleteSnapshotResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteSnapshotResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteSnapshotResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteSnapshotResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteSnapshotResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteSnapshotResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// One page of live read snapshots.
var (
	listSnapshotsResponseFieldNamespaceID = big.NewInt(1 << 0)
	listSnapshotsResponseFieldNextCursor  = big.NewInt(1 << 1)
	listSnapshotsResponseFieldSnapshots   = big.NewInt(1 << 2)
)

type ListSnapshotsResponse struct {
	// Namespace the snapshots belong to.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Opaque cursor for the next page.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// Live snapshot records in ascending snapshot-id order.
	Snapshots []*Snapshot `json:"snapshots" url:"snapshots"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSnapshotsResponse) GetNamespaceID() NamespaceID {
	if l == nil {
		return ""
	}
	return l.NamespaceID
}

func (l *ListSnapshotsResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListSnapshotsResponse) GetSnapshots() []*Snapshot {
	if l == nil {
		return nil
	}
	return l.Snapshots
}

func (l *ListSnapshotsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSnapshotsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsResponse) SetNamespaceID(namespaceID NamespaceID) {
	l.NamespaceID = namespaceID
	l.require(listSnapshotsResponseFieldNamespaceID)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsResponse) SetNextCursor(nextCursor *string) {
	l.NextCursor = nextCursor
	l.require(listSnapshotsResponseFieldNextCursor)
}

// SetSnapshots sets the Snapshots field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSnapshotsResponse) SetSnapshots(snapshots []*Snapshot) {
	l.Snapshots = snapshots
	l.require(listSnapshotsResponseFieldSnapshots)
}

func (l *ListSnapshotsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSnapshotsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSnapshotsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSnapshotsResponse) MarshalJSON() ([]byte, error) {
	type embed ListSnapshotsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSnapshotsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// A live snapshot.
var (
	snapshotFieldCreatedAtMs = big.NewInt(1 << 0)
	snapshotFieldExpiresAtMs = big.NewInt(1 << 1)
	snapshotFieldHeadSeq     = big.NewInt(1 << 2)
	snapshotFieldName        = big.NewInt(1 << 3)
	snapshotFieldNamespaceID = big.NewInt(1 << 4)
	snapshotFieldSnapshotID  = big.NewInt(1 << 5)
)

type Snapshot struct {
	// Time the snapshot record was created, in Unix milliseconds.
	CreatedAtMs int64 `json:"created_at_ms" url:"created_at_ms"`
	// When the snapshot expires, in Unix milliseconds.
	ExpiresAtMs int64 `json:"expires_at_ms" url:"expires_at_ms"`
	// Namespace sequence captured by the snapshot.
	HeadSeq ChangeSeq `json:"head_seq" url:"head_seq"`
	// Snapshot label.
	Name string `json:"name" url:"name"`
	// Namespace whose state the snapshot captured.
	NamespaceID NamespaceID `json:"namespace_id" url:"namespace_id"`
	// Snapshot id.
	SnapshotID CheckpointID `json:"snapshot_id" url:"snapshot_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *Snapshot) GetCreatedAtMs() int64 {
	if s == nil {
		return 0
	}
	return s.CreatedAtMs
}

func (s *Snapshot) GetExpiresAtMs() int64 {
	if s == nil {
		return 0
	}
	return s.ExpiresAtMs
}

func (s *Snapshot) GetHeadSeq() ChangeSeq {
	if s == nil {
		return 0
	}
	return s.HeadSeq
}

func (s *Snapshot) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Snapshot) GetNamespaceID() NamespaceID {
	if s == nil {
		return ""
	}
	return s.NamespaceID
}

func (s *Snapshot) GetSnapshotID() CheckpointID {
	if s == nil {
		return ""
	}
	return s.SnapshotID
}

func (s *Snapshot) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *Snapshot) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCreatedAtMs sets the CreatedAtMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Snapshot) SetCreatedAtMs(createdAtMs int64) {
	s.CreatedAtMs = createdAtMs
	s.require(snapshotFieldCreatedAtMs)
}

// SetExpiresAtMs sets the ExpiresAtMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Snapshot) SetExpiresAtMs(expiresAtMs int64) {
	s.ExpiresAtMs = expiresAtMs
	s.require(snapshotFieldExpiresAtMs)
}

// SetHeadSeq sets the HeadSeq field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Snapshot) SetHeadSeq(headSeq ChangeSeq) {
	s.HeadSeq = headSeq
	s.require(snapshotFieldHeadSeq)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Snapshot) SetName(name string) {
	s.Name = name
	s.require(snapshotFieldName)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Snapshot) SetNamespaceID(namespaceID NamespaceID) {
	s.NamespaceID = namespaceID
	s.require(snapshotFieldNamespaceID)
}

// SetSnapshotID sets the SnapshotID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Snapshot) SetSnapshotID(snapshotID CheckpointID) {
	s.SnapshotID = snapshotID
	s.require(snapshotFieldSnapshotID)
}

func (s *Snapshot) UnmarshalJSON(data []byte) error {
	type unmarshaler Snapshot
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = Snapshot(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *Snapshot) MarshalJSON() ([]byte, error) {
	type embed Snapshot
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *Snapshot) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
