// Code generated by Fern. DO NOT EDIT.

package changes

import (
	context "context"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	core "github.com/loonfs/loonfs-sdk-go/core"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	option "github.com/loonfs/loonfs-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns committed changes after a sequence. A snapshot limits the feed to its captured sequence.
//
// Example:
//
//	request := &loonfs.ListChangesRequest{
//	    NamespaceID: "namespace_id",
//	    AfterSeq: int64(1000000),
//	    SnapshotID: loonfs.String(
//	        "chk_00000000000000000000000000000002",
//	    ),
//	}
//	client.Changes.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *loonfs.ListChangesRequest,
	opts ...option.RequestOption,
) (*loonfs.ListChangesResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
