// Code generated by Fern. DO NOT EDIT.

package filesystem_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	option "github.com/loonfs/loonfs-sdk-go/option"
	server "github.com/loonfs/loonfs-sdk-go/server"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestFilesystemListChangesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.ListChangesRequest{
		NamespaceID: "namespace_id",
		AfterSeq:    int64(1000000),
		SnapshotID: loonfs.String(
			"chk_00000000000000000000000000000002",
		),
	}
	_, invocationErr := client.Filesystem.ListChanges(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesystemListChangesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesystemListChangesWithWireMock", "GET", "/v0/namespaces/namespace_id/changes", map[string]interface{}{"after_seq": "1000000", "snapshot_id": "chk_00000000000000000000000000000002"}, 1)
}

func TestFilesystemCreateCommitWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.CommitRequest{
		NamespaceID: "namespace_id",
		Actor: &loonfs.ActorRef{
			ID:   "usr_8f3c",
			Kind: loonfs.ActorKindUser,
		},
		CommitID: "c_f3a9c2d4b6e8417a90c5d2f8e1b7a6c0",
		Operations: []*loonfs.FilesystemOperation{
			&loonfs.FilesystemOperation{
				CreateDirectory: &loonfs.FilesystemOperationCreateDirectory{
					Path: "/docs/report.txt",
				},
			},
		},
	}
	_, invocationErr := client.Filesystem.CreateCommit(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesystemCreateCommitWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesystemCreateCommitWithWireMock", "POST", "/v0/namespaces/namespace_id/commits", nil, 1)
}

func TestFilesystemCreateDownloadWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.BeginDownloadRequest{
		NamespaceID: "namespace_id",
		SnapshotID: loonfs.String(
			"chk_00000000000000000000000000000002",
		),
		Path: "/docs/report.txt",
	}
	_, invocationErr := client.Filesystem.CreateDownload(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesystemCreateDownloadWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesystemCreateDownloadWithWireMock", "POST", "/v0/namespaces/namespace_id/filesystem/downloads", map[string]interface{}{"snapshot_id": "chk_00000000000000000000000000000002"}, 1)
}

func TestFilesystemListPathEntriesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.ListPathEntriesRequest{
		NamespaceID: "namespace_id",
		Path:        "path",
		SnapshotID: loonfs.String(
			"chk_00000000000000000000000000000002",
		),
	}
	_, invocationErr := client.Filesystem.ListPathEntries(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesystemListPathEntriesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesystemListPathEntriesWithWireMock", "GET", "/v0/namespaces/namespace_id/filesystem/entries", map[string]interface{}{"path": "path", "snapshot_id": "chk_00000000000000000000000000000002"}, 1)
}

func TestFilesystemGetPathEntryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.GetPathEntryRequest{
		NamespaceID: "namespace_id",
		Path:        "path",
		SnapshotID: loonfs.String(
			"chk_00000000000000000000000000000002",
		),
	}
	_, invocationErr := client.Filesystem.GetPathEntry(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesystemGetPathEntryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesystemGetPathEntryWithWireMock", "GET", "/v0/namespaces/namespace_id/filesystem/entry", map[string]interface{}{"path": "path", "snapshot_id": "chk_00000000000000000000000000000002"}, 1)
}

func TestFilesystemListFileRevisionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.ListFileRevisionsRequest{
		NamespaceID: "namespace_id",
		Path:        "path",
	}
	_, invocationErr := client.Filesystem.ListFileRevisions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesystemListFileRevisionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesystemListFileRevisionsWithWireMock", "GET", "/v0/namespaces/namespace_id/filesystem/revisions", map[string]interface{}{"path": "path"}, 1)
}

func TestFilesystemListTrashWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.ListTrashRequest{
		NamespaceID: "namespace_id",
	}
	_, invocationErr := client.Filesystem.ListTrash(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesystemListTrashWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesystemListTrashWithWireMock", "GET", "/v0/namespaces/namespace_id/filesystem/trash", nil, 1)
}
