// Code generated by Fern. DO NOT EDIT.

package admin_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	option "github.com/loonfs/loonfs-sdk-go/option"
	server "github.com/loonfs/loonfs-sdk-go/server"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAdminListCheckpointsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.ListCheckpointsRequest{
		NamespaceID: "namespace_id",
	}
	_, invocationErr := client.Admin.ListCheckpoints(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminListCheckpointsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminListCheckpointsWithWireMock", "GET", "/v0/admin/namespaces/namespace_id/checkpoints", nil, 1)
}

func TestAdminCreateCheckpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.CreateCheckpointRequest{
		NamespaceID: "namespace_id",
		Name:        "name",
	}
	_, invocationErr := client.Admin.CreateCheckpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminCreateCheckpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminCreateCheckpointWithWireMock", "POST", "/v0/admin/namespaces/namespace_id/checkpoints", nil, 1)
}

func TestAdminReleaseCheckpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.ReleaseCheckpointRequest{
		NamespaceID:  "namespace_id",
		CheckpointID: "checkpoint_id",
	}
	_, invocationErr := client.Admin.ReleaseCheckpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminReleaseCheckpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminReleaseCheckpointWithWireMock", "POST", "/v0/admin/namespaces/namespace_id/checkpoints/checkpoint_id/release", nil, 1)
}

func TestAdminGetNamespaceDiagnosticsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.GetNamespaceDiagnosticsRequest{
		NamespaceID: "namespace_id",
	}
	_, invocationErr := client.Admin.GetNamespaceDiagnostics(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminGetNamespaceDiagnosticsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminGetNamespaceDiagnosticsWithWireMock", "GET", "/v0/admin/namespaces/namespace_id/diagnostics", nil, 1)
}

func TestAdminGetGrepIndexWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.GetGrepIndexRequest{
		NamespaceID: "namespace_id",
	}
	_, invocationErr := client.Admin.GetGrepIndex(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminGetGrepIndexWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminGetGrepIndexWithWireMock", "GET", "/v0/admin/namespaces/namespace_id/grep/index", nil, 1)
}

func TestAdminDisableGrepIndexWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.DisableGrepIndexRequest{
		NamespaceID: "namespace_id",
	}
	_, invocationErr := client.Admin.DisableGrepIndex(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminDisableGrepIndexWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminDisableGrepIndexWithWireMock", "POST", "/v0/admin/namespaces/namespace_id/grep/index/disable", nil, 1)
}

func TestAdminEnableGrepIndexWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.EnableGrepIndexRequest{
		NamespaceID: "namespace_id",
	}
	_, invocationErr := client.Admin.EnableGrepIndex(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminEnableGrepIndexWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminEnableGrepIndexWithWireMock", "POST", "/v0/admin/namespaces/namespace_id/grep/index/enable", nil, 1)
}

func TestAdminGcGrepIndexWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.GrepGcRequest{
		NamespaceID: "namespace_id",
	}
	_, invocationErr := client.Admin.GcGrepIndex(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminGcGrepIndexWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminGcGrepIndexWithWireMock", "POST", "/v0/admin/namespaces/namespace_id/grep/index/gc", nil, 1)
}

func TestAdminRunMaintenanceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.MaintenanceStepRequest{
		NamespaceID: "namespace_id",
	}
	_, invocationErr := client.Admin.RunMaintenance(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminRunMaintenanceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminRunMaintenanceWithWireMock", "POST", "/v0/admin/namespaces/namespace_id/maintenance/run", nil, 1)
}

func TestAdminProbeStoreWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := map[string]any{
		"key": "value",
	}
	_, invocationErr := client.Admin.ProbeStore(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAdminProbeStoreWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAdminProbeStoreWithWireMock", "POST", "/v0/admin/store/probe", nil, 1)
}
