// Code generated by Fern. DO NOT EDIT.

package diagnostics

import (
	context "context"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	core "github.com/loonfs/loonfs-sdk-go/core"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	maintenance "github.com/loonfs/loonfs-sdk-go/maintenance"
	option "github.com/loonfs/loonfs-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns namespace state together with the current manifest and visible WAL tail.
//
// Example:
//
//	request := &maintenance.GetNamespaceDiagnosticsRequest{
//	    NamespaceID: "namespace_id",
//	}
//	client.Maintenance.Diagnostics.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *maintenance.GetNamespaceDiagnosticsRequest,
	opts ...option.RequestOption,
) (*loonfs.NamespaceDiagnostics, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
