// Code generated by Fern. DO NOT EDIT.

package checkpoints

import (
	context "context"
	http "net/http"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	core "github.com/loonfs/loonfs-sdk-go/core"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	maintenance "github.com/loonfs/loonfs-sdk-go/maintenance"
	option "github.com/loonfs/loonfs-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Create(
	ctx context.Context,
	request *maintenance.CreateCheckpointRequest,
	opts ...option.RequestOption,
) (*core.Response[*loonfs.Checkpoint], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/maintenance/namespaces/%v/checkpoints",
		request.NamespaceID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *loonfs.Checkpoint
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  true,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(maintenance.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*loonfs.Checkpoint]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Delete(
	ctx context.Context,
	request *maintenance.DeleteCheckpointRequest,
	opts ...option.RequestOption,
) (*core.Response[*loonfs.DeleteCheckpointResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/maintenance/namespaces/%v/checkpoints/%v",
		request.NamespaceID,
		request.CheckpointID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *loonfs.DeleteCheckpointResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(maintenance.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*loonfs.DeleteCheckpointResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
