// Code generated by Fern. DO NOT EDIT.

package grepindex

import (
	context "context"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	core "github.com/loonfs/loonfs-sdk-go/core"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	maintenance "github.com/loonfs/loonfs-sdk-go/maintenance"
	option "github.com/loonfs/loonfs-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns whether the namespace's grep index is `disabled`, `backfilling`, or `active`, including build progress when available. A namespace that has never enabled the index is `disabled`. This operation requires a deployment that maintains grep indexes and does not change the index.
//
// Example:
//
//	request := &maintenance.GetGrepIndexRequest{
//	    NamespaceID: "namespace_id",
//	}
//	client.Maintenance.GrepIndex.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *maintenance.GetGrepIndexRequest,
	opts ...option.RequestOption,
) (*loonfs.GrepIndex, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Disables the namespace's grep index by publishing the next manifest number with no segment references. Index maintenance stops when a step reads the disabled manifest. Explicit grep garbage collection later reclaims the segments. Idempotent. Requires this deployment to maintain the grep index.
//
// Example:
//
//	request := &maintenance.DisableGrepIndexRequest{
//	    NamespaceID: "namespace_id",
//	}
//	client.Maintenance.GrepIndex.Disable(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Disable(
	ctx context.Context,
	request *maintenance.DisableGrepIndexRequest,
	opts ...option.RequestOption,
) (*loonfs.GrepIndex, error) {
	response, err := c.WithRawResponse.Disable(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Enables the namespace's grep index and asks this deployment's maintenance runner for the backfill's first step. The response reports the lifecycle and bookkeeping read after the transition: a fresh enable is `backfilling` with the sequence its checkpoint captured, while an already-enabled namespace answers with its current status. Idempotent. Requires this deployment to maintain the grep index.
//
// Example:
//
//	request := &maintenance.EnableGrepIndexRequest{
//	    NamespaceID: "namespace_id",
//	}
//	client.Maintenance.GrepIndex.Enable(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Enable(
	ctx context.Context,
	request *maintenance.EnableGrepIndexRequest,
	opts ...option.RequestOption,
) (*loonfs.GrepIndex, error) {
	response, err := c.WithRawResponse.Enable(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Runs one explicit garbage-collection pass over only this namespace's grep-owned extension keyspace. A tombstoned or absent namespace has aged extension state reaped. Every call reads durable roots and completes one pass. Unreadable or invalid roots fail before deletion. Requires this deployment to maintain the grep index.
//
// Example:
//
//	request := &maintenance.GcGrepIndexRequest{
//	    NamespaceID: "namespace_id",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Maintenance.GrepIndex.Gc(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Gc(
	ctx context.Context,
	request *maintenance.GcGrepIndexRequest,
	opts ...option.RequestOption,
) (*loonfs.GrepGcResponse, error) {
	response, err := c.WithRawResponse.Gc(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
