// Code generated by Fern. DO NOT EDIT.

package server

import (
	client "github.com/loonfs/loonfs-sdk-go/admin/client"
	capabilities "github.com/loonfs/loonfs-sdk-go/capabilities"
	changes "github.com/loonfs/loonfs-sdk-go/changes"
	commits "github.com/loonfs/loonfs-sdk-go/commits"
	core "github.com/loonfs/loonfs-sdk-go/core"
	files "github.com/loonfs/loonfs-sdk-go/files"
	inodes "github.com/loonfs/loonfs-sdk-go/inodes"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	namespaces "github.com/loonfs/loonfs-sdk-go/namespaces"
	option "github.com/loonfs/loonfs-sdk-go/option"
	snapshots "github.com/loonfs/loonfs-sdk-go/snapshots"
	trash "github.com/loonfs/loonfs-sdk-go/trash"
	uploads "github.com/loonfs/loonfs-sdk-go/uploads"
)

type Client struct {
	Capabilities *capabilities.Client
	Namespaces   *namespaces.Client
	Changes      *changes.Client
	Commits      *commits.Client
	Files        *files.Client
	Trash        *trash.Client
	Inodes       *inodes.Client
	Snapshots    *snapshots.Client
	Uploads      *uploads.Client
	Admin        *client.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Capabilities: capabilities.NewClient(options),
		Namespaces:   namespaces.NewClient(options),
		Changes:      changes.NewClient(options),
		Commits:      commits.NewClient(options),
		Files:        files.NewClient(options),
		Trash:        trash.NewClient(options),
		Inodes:       inodes.NewClient(options),
		Snapshots:    snapshots.NewClient(options),
		Uploads:      uploads.NewClient(options),
		Admin:        client.NewClient(options),
		options:      options,
		baseURL:      options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
