// Code generated by Fern. DO NOT EDIT.

package server

import (
	admin "github.com/loonfs/loonfs-sdk-go/admin"
	core "github.com/loonfs/loonfs-sdk-go/core"
	filesystem "github.com/loonfs/loonfs-sdk-go/filesystem"
	inodes "github.com/loonfs/loonfs-sdk-go/inodes"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	namespaces "github.com/loonfs/loonfs-sdk-go/namespaces"
	option "github.com/loonfs/loonfs-sdk-go/option"
	query "github.com/loonfs/loonfs-sdk-go/query"
	system "github.com/loonfs/loonfs-sdk-go/system"
	uploads "github.com/loonfs/loonfs-sdk-go/uploads"
)

type Client struct {
	System     *system.Client
	Admin      *admin.Client
	Namespaces *namespaces.Client
	Filesystem *filesystem.Client
	Query      *query.Client
	Inodes     *inodes.Client
	Uploads    *uploads.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		System:     system.NewClient(options),
		Admin:      admin.NewClient(options),
		Namespaces: namespaces.NewClient(options),
		Filesystem: filesystem.NewClient(options),
		Query:      query.NewClient(options),
		Inodes:     inodes.NewClient(options),
		Uploads:    uploads.NewClient(options),
		options:    options,
		baseURL:    options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
