// Code generated by Fern. DO NOT EDIT.

package system

import (
	context "context"

	core "github.com/loonfs/loonfs-sdk-go/core"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	option "github.com/loonfs/loonfs-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns `ok` when the server is running and can accept requests.
//
// Example:
//
//	client.System.Health(
//	    context.TODO(),
//	)
func (c *Client) Health(
	ctx context.Context,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.Health(
		ctx,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}

// Returns this process's metrics in Prometheus text exposition format 0.0.4. Unlike `/health` and `/readiness`, the route requires the deployment's bearer token.
//
// Example:
//
//	client.System.GetMetrics(
//	    context.TODO(),
//	)
func (c *Client) GetMetrics(
	ctx context.Context,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.GetMetrics(
		ctx,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}

// Returns `ready` while the server admits new work. Once shutdown begins and publisher admission closes, answers 503 `shutting_down` so load balancers can drain the instance. `/health` stays the liveness probe: it only reports that the process is up.
//
// Example:
//
//	client.System.Readiness(
//	    context.TODO(),
//	)
func (c *Client) Readiness(
	ctx context.Context,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.Readiness(
		ctx,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}
