// Code generated by Fern. DO NOT EDIT.

package admin

import (
	big "math/big"
)

var (
	getNamespaceDiagnosticsRequestFieldNamespaceID = big.NewInt(1 << 0)
)

type GetNamespaceDiagnosticsRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetNamespaceDiagnosticsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNamespaceDiagnosticsRequest) SetNamespaceID(namespaceID string) {
	g.NamespaceID = namespaceID
	g.require(getNamespaceDiagnosticsRequestFieldNamespaceID)
}
