// Code generated by Fern. DO NOT EDIT.

package admin

import (
	json "encoding/json"
	loonfssdkgo "github.com/loonfs/loonfs-sdk-go"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	big "math/big"
)

var (
	maintenanceStepRequestFieldNamespaceID         = big.NewInt(1 << 0)
	maintenanceStepRequestFieldGc                  = big.NewInt(1 << 1)
	maintenanceStepRequestFieldMetadataMaintenance = big.NewInt(1 << 2)
	maintenanceStepRequestFieldRetention           = big.NewInt(1 << 3)
)

type MaintenanceStepRequest struct {
	// Namespace id
	NamespaceID string `json:"-" url:"-"`
	// Run one bounded mark-and-sweep garbage-collection pass. Omit this
	// field to skip garbage collection.
	Gc *loonfssdkgo.GcRequest `json:"gc,omitempty" url:"-"`
	// Flush the visible WAL tail into metadata segments, then run one bounded
	// reorganization step.
	MetadataMaintenance *loonfssdkgo.MetadataMaintenanceRequest `json:"metadata_maintenance,omitempty" url:"-"`
	// Advance the retention floor to the flushed manifest head. Include this
	// field to select the action.
	Retention *loonfssdkgo.AdvanceRetentionRequest `json:"retention,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MaintenanceStepRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetNamespaceID sets the NamespaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MaintenanceStepRequest) SetNamespaceID(namespaceID string) {
	m.NamespaceID = namespaceID
	m.require(maintenanceStepRequestFieldNamespaceID)
}

// SetGc sets the Gc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MaintenanceStepRequest) SetGc(gc *loonfssdkgo.GcRequest) {
	m.Gc = gc
	m.require(maintenanceStepRequestFieldGc)
}

// SetMetadataMaintenance sets the MetadataMaintenance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MaintenanceStepRequest) SetMetadataMaintenance(metadataMaintenance *loonfssdkgo.MetadataMaintenanceRequest) {
	m.MetadataMaintenance = metadataMaintenance
	m.require(maintenanceStepRequestFieldMetadataMaintenance)
}

// SetRetention sets the Retention field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MaintenanceStepRequest) SetRetention(retention *loonfssdkgo.AdvanceRetentionRequest) {
	m.Retention = retention
	m.require(maintenanceStepRequestFieldRetention)
}

func (m *MaintenanceStepRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MaintenanceStepRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MaintenanceStepRequest(body)
	return nil
}

func (m *MaintenanceStepRequest) MarshalJSON() ([]byte, error) {
	type embed MaintenanceStepRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}
