// Code generated by Fern. DO NOT EDIT.

package namespaces

import (
	context "context"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	core "github.com/loonfs/loonfs-sdk-go/core"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	option "github.com/loonfs/loonfs-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Creates a new empty namespace.
//
// Example:
//
//	request := &loonfs.CreateNamespaceRequest{
//	    NamespaceID: "demo",
//	}
//	client.Namespaces.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *loonfs.CreateNamespaceRequest,
	opts ...option.RequestOption,
) (*loonfs.Namespace, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the current head and retention state for a namespace.
//
// Example:
//
//	request := &loonfs.GetNamespaceRequest{
//	    NamespaceID: "namespace_id",
//	}
//	client.Namespaces.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *loonfs.GetNamespaceRequest,
	opts ...option.RequestOption,
) (*loonfs.Namespace, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Marks a namespace as deleted.
//
// Example:
//
//	request := &loonfs.DeleteNamespaceRequest{
//	    NamespaceID: "namespace_id",
//	}
//	client.Namespaces.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *loonfs.DeleteNamespaceRequest,
	opts ...option.RequestOption,
) (*loonfs.DeleteNamespaceResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new namespace as a fork from the source namespace's current durable view.
//
// Example:
//
//	request := &loonfs.ForkNamespaceRequest{
//	    NamespaceID: "namespace_id",
//	    NewNamespaceID: "demo",
//	}
//	client.Namespaces.Fork(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Fork(
	ctx context.Context,
	request *loonfs.ForkNamespaceRequest,
	opts ...option.RequestOption,
) (*loonfs.Namespace, error) {
	response, err := c.WithRawResponse.Fork(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
