// Code generated by Fern. DO NOT EDIT.

package diagnostics

import (
	context "context"
	http "net/http"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	admin "github.com/loonfs/loonfs-sdk-go/admin"
	core "github.com/loonfs/loonfs-sdk-go/core"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	option "github.com/loonfs/loonfs-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Retrieve(
	ctx context.Context,
	request *admin.GetNamespaceDiagnosticsRequest,
	opts ...option.RequestOption,
) (*core.Response[*loonfs.NamespaceDiagnostics], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/admin/namespaces/%v/diagnostics",
		request.NamespaceID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *loonfs.NamespaceDiagnostics
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(admin.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*loonfs.NamespaceDiagnostics]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
