// Code generated by Fern. DO NOT EDIT.

package uploads_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	server "github.com/loonfs/loonfs-sdk-go/server"
	option "github.com/loonfs/loonfs-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestUploadsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.CreateUploadRequest{
		NamespaceID: "namespace_id",
		Body: &loonfs.BeginUploadRequest{
			ServiceProxied: &loonfs.BeginUploadServiceProxied{},
		},
	}
	_, invocationErr := client.Uploads.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUploadsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUploadsCreateWithWireMock", "POST", "/v0/namespaces/namespace_id/uploads", nil, 1)
}

func TestUploadsRetrieveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.GetUploadRequest{
		NamespaceID: "namespace_id",
		UploadID:    "upload_id",
	}
	_, invocationErr := client.Uploads.Retrieve(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUploadsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUploadsRetrieveWithWireMock", "GET", "/v0/namespaces/namespace_id/uploads/upload_id", nil, 1)
}

func TestUploadsAbortWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.AbortUploadRequest{
		NamespaceID: "namespace_id",
		UploadID:    "upload_id",
	}
	_, invocationErr := client.Uploads.Abort(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUploadsAbortWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUploadsAbortWithWireMock", "POST", "/v0/namespaces/namespace_id/uploads/upload_id/abort", nil, 1)
}

func TestUploadsCompleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.CompleteUploadRequest{
		NamespaceID: "namespace_id",
		UploadID:    "upload_id",
		Body: &loonfs.UploadCompletion{
			ServiceProxied: &loonfs.CompleteUploadServiceProxied{},
		},
	}
	_, invocationErr := client.Uploads.Complete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUploadsCompleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUploadsCompleteWithWireMock", "POST", "/v0/namespaces/namespace_id/uploads/upload_id/complete", nil, 1)
}

func TestUploadsSignPartsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := server.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &loonfs.SignUploadPartsRequest{
		NamespaceID: "namespace_id",
		UploadID:    "upload_id",
		Parts: []*loonfs.UploadPartChecksumClaim{
			&loonfs.UploadPartChecksumClaim{
				Checksum: &loonfs.Checksum{
					Algorithm: loonfs.ChecksumAlgorithmSha256,
					Value:     "value",
				},
				PartNumber: 1,
			},
		},
	}
	_, invocationErr := client.Uploads.SignParts(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUploadsSignPartsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUploadsSignPartsWithWireMock", "POST", "/v0/namespaces/namespace_id/uploads/upload_id/parts", nil, 1)
}
