// Code generated by Fern. DO NOT EDIT.

package capabilities

import (
	context "context"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	core "github.com/loonfs/loonfs-sdk-go/core"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	option "github.com/loonfs/loonfs-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns a summary of supported features and limits.
//
// Example:
//
//	client.Capabilities.Retrieve(
//	    context.TODO(),
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	opts ...option.RequestOption,
) (*loonfs.CapabilityDocument, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
