// Code generated by Fern. DO NOT EDIT.

package uploads

import (
	context "context"
	io "io"

	loonfs "github.com/loonfs/loonfs-sdk-go"
	core "github.com/loonfs/loonfs-sdk-go/core"
	internal "github.com/loonfs/loonfs-sdk-go/internal"
	option "github.com/loonfs/loonfs-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Starts an upload session for content that may later be attached to a file. Service-proxied uploads send bytes through the server; direct-put uploads return object-store presigned credentials.
//
// Example:
//
//	request := &loonfs.CreateUploadRequest{
//	    NamespaceID: "namespace_id",
//	    Body: &loonfs.BeginUploadRequest{
//	        ServiceProxied: &loonfs.BeginUploadServiceProxied{},
//	    },
//	}
//	client.Uploads.CreateUpload(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateUpload(
	ctx context.Context,
	request *loonfs.CreateUploadRequest,
	opts ...option.RequestOption,
) (*loonfs.BeginUploadResponse, error) {
	response, err := c.WithRawResponse.CreateUpload(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns an upload session. A completed session includes a new content token so the client can retry the commit without uploading the content again.
//
// Example:
//
//	request := &loonfs.GetUploadRequest{
//	    NamespaceID: "namespace_id",
//	    UploadID: "upload_id",
//	}
//	client.Uploads.GetUpload(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetUpload(
	ctx context.Context,
	request *loonfs.GetUploadRequest,
	opts ...option.RequestOption,
) (*loonfs.UploadSession, error) {
	response, err := c.WithRawResponse.GetUpload(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Ends an upload session without selecting content and deletes the object it was writing. Repeating it succeeds; a session that already completed cannot be aborted.
//
// Example:
//
//	request := &loonfs.AbortUploadRequest{
//	    NamespaceID: "namespace_id",
//	    UploadID: "upload_id",
//	}
//	client.Uploads.AbortUpload(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) AbortUpload(
	ctx context.Context,
	request *loonfs.AbortUploadRequest,
	opts ...option.RequestOption,
) (*loonfs.UploadSession, error) {
	response, err := c.WithRawResponse.AbortUpload(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Completes an upload. The request mode must match the mode used to start the session. Direct uploads include a content claim; multipart also includes completed parts.
//
// Example:
//
//	request := &loonfs.CompleteUploadBody{
//	    NamespaceID: "namespace_id",
//	    UploadID: "upload_id",
//	    Body: &loonfs.CompleteUploadRequest{
//	        ServiceProxied: &loonfs.CompleteUploadServiceProxied{},
//	    },
//	}
//	client.Uploads.CompleteUpload(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CompleteUpload(
	ctx context.Context,
	request *loonfs.CompleteUploadBody,
	opts ...option.RequestOption,
) (*loonfs.UploadSession, error) {
	response, err := c.WithRawResponse.CompleteUpload(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Uploads bytes into a service-proxied upload session and returns the content reference for the stored object.
func (c *Client) PutUploadContent(
	ctx context.Context,
	// Namespace id
	namespaceID string,
	// Upload session id
	uploadID string,
	request io.Reader,
	opts ...option.RequestOption,
) (*loonfs.UploadContentResponse, error) {
	response, err := c.WithRawResponse.PutUploadContent(
		ctx,
		namespaceID,
		uploadID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns one short-lived, checksum-bound upload capability per requested part of an open direct_multipart session. Asking again for a part is how a client retries it.
//
// Example:
//
//	request := &loonfs.SignUploadPartsRequest{
//	    NamespaceID: "namespace_id",
//	    UploadID: "upload_id",
//	    Parts: []*loonfs.UploadPartChecksumClaim{
//	        &loonfs.UploadPartChecksumClaim{
//	            Checksum: &loonfs.Checksum{
//	                Algorithm: loonfs.ChecksumAlgorithmSha256,
//	                Value: "value",
//	            },
//	            PartNumber: 1,
//	        },
//	    },
//	}
//	client.Uploads.SignUploadParts(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SignUploadParts(
	ctx context.Context,
	request *loonfs.SignUploadPartsRequest,
	opts ...option.RequestOption,
) (*loonfs.SignUploadPartsResponse, error) {
	response, err := c.WithRawResponse.SignUploadParts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
